### ISSUE TITLE
Error in new account_payment_order migration script

### ISSUE THREAD

**Issue by ddejong-therp** [OCA/bank-payment#1010]
## Module
account_payment_order

## Describe the bug
Our migration of an enterprise 10 to 14 database failed last night because of the following.
The new migration script seems to create new account move lines here [corrected]: https://github.com/OCA/bank-payment/blob/041b25fdd02d3183e5540a8900554c269d6cd9a5/account_payment_order/migrations/14.0.2.0.0/post-migration.py#L127
Yet, it creates it without an `account_id` or `display_type`, which goes against this constraint: https://github.com/OCA/OCB/blob/14.0/addons/account/models/account_move.py#L3344

Edit: Stacktrace:
```
2023-01-02 01:13:22,299 2199 WARNING fresh odoo.modules.loading: Transient module states were reset 
2023-01-02 01:13:22,301 2199 ERROR fresh odoo.modules.registry: Failed to load registry 
2023-01-02 01:13:22,301 2199 CRITICAL fresh odoo.service.server: Failed to initialize database `fresh`. 
Traceback (most recent call last):
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/modules/loading.py", line 457, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/ubuntu/odoo/.venv/src/openupgradelib/openupgradelib/openupgrade.py", line 1876, in wrapped_function
    if use_env2 else cr, version)
  File "/home/ubuntu/odoo/auto/addons/account_payment_order/migrations/14.0.2.0.0/post-migration.py", line 169, in migrate
    create_moves_from_orphan_account_payments(env)
  File "/home/ubuntu/odoo/auto/addons/account_payment_order/migrations/14.0.2.0.0/post-migration.py", line 127, in create_moves_from_orphan_account_payments
    payment._synchronize_to_moves(["date"])  # no more changed fields needed
  File "/home/ubuntu/odoo/auto/addons/account/models/account_payment.py", line 823, in _synchronize_to_moves
    'line_ids': line_ids_commands,
  File "/home/ubuntu/odoo/auto/addons/purchase/models/account_invoice.py", line 121, in write
    res = super(AccountMove, self).write(vals)
  File "/home/ubuntu/odoo/auto/addons/l10n_nl_tax_statement/models/account_move.py", line 34, in write
    return super().write(values)
  File "/home/ubuntu/odoo/auto/addons/account/models/account_move.py", line 2071, in write
    res = super(AccountMove, self.with_context(check_move_validity=False, skip_account_move_synchronization=True)).write(vals)
  File "/home/ubuntu/odoo/auto/addons/mail/models/mail_thread.py", line 316, in write
    return super(MailThread, self).write(values)
  File "/home/ubuntu/odoo/auto/addons/mail/models/mail_activity.py", line 788, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/ubuntu/odoo/auto/addons/component_event/models/base.py", line 109, in write
    result = super(Base, self).write(vals)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/models.py", line 3680, in write
    field.write(self, vals[fname])
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/fields.py", line 3052, in write
    return self.write_batch([(records, value)])
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/fields.py", line 3073, in write_batch
    return self.write_real(records_commands_list, create)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/fields.py", line 3249, in write_real
    flush()
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/fields.py", line 3211, in flush
    comodel.create(to_create)
  File "<decorator-gen-195>", line 2, in create
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/ubuntu/odoo/auto/addons/account/models/account_move.py", line 4168, in create
    lines = super(AccountMoveLine, self).create(vals_list)
  File "<decorator-gen-125>", line 2, in create
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/ubuntu/odoo/auto/addons/component_event/models/base.py", line 102, in create
    records = super(Base, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/models.py", line 3885, in create
    records = self._create(data_list)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/models.py", line 3991, in _create
    cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/ubuntu/odoo/custom/src/odoo/odoo/sql_db.py", line 300, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.CheckViolation: new row for relation "account_move_line" violates check constraint "account_move_line_check_accountable_required_fields"
DETAIL:  Failing row contains (616924, 1, 2023-01-02 01:13:15.123879, 2023-01-02 01:13:15.123879, 1, null, null, 1, 2021-07-19, 5810, null, 0.00, null, 1, null, 11001.39, f, null, null, null, null, 148712, ID-25060, null, null, null, null, 11001.39, 1.00, null, null, null, null, null, null, 1, null, null, null, null, t, null, null, null, null, null, null, null, null, null, null, 10, 0, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null)
```

**Comment by pedrobaeza** [comment]
That's not true...

First, the line you mention is the header (move) creation, and second, the move lines creation is done through this call:

https://github.com/OCA/bank-payment/blob/041b25fdd02d3183e5540a8900554c269d6cd9a5/account_payment_order/migrations/14.0.2.0.0/post-migration.py#L127

**Comment by ddejong-therp** [comment]
Ah! My bad. My head must have still been sleeping this first monday of the year..

I've added the actual stack trace now. I haven't looked to deep into it yet to figure out why it creates the `account.move.line`'s without those fields.

**Comment by pedrobaeza** [comment]
It can be that the used journal doesn't have default accounts set in it.
