### ISSUE TITLE
Error after update odoo14.0 (TypeError: Model 'bank.payment.line' does not exist in registry.)

### ISSUE THREAD

**Issue by edsonblwolf** [OCA/bank-payment#1012]
2023-01-04 01:15:54,625 2023 WARNING wnetinfo odoo.modules.loading: Transient module states were reset 
2023-01-04 01:15:54,625 2023 ERROR wnetinfo odoo.modules.registry: Failed to load registry 
2023-01-04 01:15:54,625 2023 ERROR wnetinfo odoo.addons.base.models.ir_cron: Unexpected exception while processing cron job {'id': 14, 'ir_actions_server_id': 254, 'cron_name': 'Post process payment transactions', 'user_id': 1, 'active': True, 'interval_number': 10, 'interval_type': 'minutes', 'numbercall': -1, 'doall': None, 'nextcall': datetime.datetime(2023, 1, 4, 1, 12, 30), 'lastcall': datetime.datetime(2023, 1, 4, 1, 2, 39), 'priority': 5, 'create_uid': 1, 'create_date': datetime.datetime(2022, 12, 22, 22, 32, 28, 926119), 'write_uid': 1, 'write_date': datetime.datetime(2023, 1, 4, 1, 11, 52, 271192)} 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 63, in __new__
    return cls.registries[db_name]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: 'wnetinfo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_cron.py", line 237, in _process_jobs
    registry = odoo.registry(db_name)
  File "/usr/lib/python3/dist-packages/odoo/__init__.py", line 104, in registry
    return modules.registry.Registry(database_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 65, in __new__
    return cls.new(db_name)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 455, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 232, in load
    model = cls._build_model(self, cr)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 554, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'bank.payment.line' does not exist in registry.
2023-01-04 01:15:56,428 2027 INFO wnetinfo odoo.addons.base.models.ir_cron: Starting job `Post process payment transactions`.

**Comment by gdgellatly** [comment]
You need to upgrade account_payment_order

**Comment by edsonblwolf** [comment]
It has been updated. After the update the error occurred.

> You need to upgrade account_payment_order

**Comment by oyale** [comment]
Ran into this issue on a fresh installation. Problem was solved updating `account_banking_*` modules to v14.0.2.0.0

**Comment by pedrobaeza** [comment]
Exactly. Please update and check if you have any extra source code pointing to `bank.payment.line`. If so, you will need to adapt it.
