### ISSUE TITLE
[8.0] Cannot load account_direct_debit with odoo code dated after 2015-01-21

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#109]
With odoo 8.0 dated after 2015-01-21, we have a crash when we start odoo:

```
2015-01-22 13:41:15,956 14029 ERROR o8_test2 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/alexis/new_boite/dev/odoo/openerp/service/server.py", line 281, in app
    return self.app(e, s)
  File "/home/alexis/new_boite/dev/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/home/alexis/new_boite/dev/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 1275, in __call__
    return self.dispatch(environ, start_response)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 1249, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 579, in __call__
    return self.app(environ, start_response)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 1407, in dispatch
    ir_http = request.registry['ir.http']
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 338, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/registry.py", line 335, in get
    update_module)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/registry.py", line 366, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/loading.py", line 152, in load_module_graph
    models = registry.load(cr, package)
  File "/home/alexis/new_boite/dev/odoo/openerp/modules/registry.py", line 162, in load
    model = cls._build_model(self, cr)
  File "/home/alexis/new_boite/dev/odoo/openerp/models.py", line 651, in _build_model
    model.__init__(pool, cr)
  File "/home/alexis/new_boite/dev/banking-80/account_direct_debit/models/account_invoice.py", line 140, in __init__
    invoice_obj._columns['state'].selection.append(
KeyError: 'state'
```

It seems we can't add an entry of a fields.selection via a hacking in **init** of the class of the object.

**Comment by alexis-via** [comment]
Sorry, it has already been fixed in OCA/banking.
