### ISSUE TITLE
8.0 Cannot even generate a SEPA credit transfer file !

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#111]
Here is the scenario on v8:
1) install the module account_banking_sepa_credit_transfer and make sure that the module account_banking_sepa_direct_debit is NOT INSTALLED
2) create a new payment order, select a payment mode for SEPA credit transfer, select an invoice, confirm
3) in the wizard pop-up, leave the default parameters and generate the XML file: here you get a crash:

```
2015-01-24 22:45:13,713 8553 ERROR o8_test2 openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 525, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 562, in dispatch
    result = self._call_function(**self.params)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 302, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 299, in checked_call
    return self.endpoint(*a, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 791, in __call__
    return self.method(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/openerp/http.py", line 395, in response_wrap
    response = f(*args, **kw)
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 953, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/alexis/new_boite/dev/odoo/addons/web/controllers/main.py", line 941, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/banking-80/account_banking_sepa_credit_transfer/wizard/export_sepa.py", line 153, in create_sepa
    cr, uid, pain_root, gen_args, context=context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/banking-80/account_banking_pain_base/models/banking_export_pain.py", line 196, in generate_group_header_block
    context=context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/banking-80/account_banking_pain_base/models/banking_export_pain.py", line 269, in generate_initiating_party_block
    context=context)
  File "/home/alexis/new_boite/dev/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/banking-80/account_banking_pain_base/models/res_company.py", line 47, in _get_initiating_party_identifier
    party_identifier = company.sepa_creditor_identifier
AttributeError: 'res.company' object has no attribute 'sepa_creditor_identifier'
```

Code analysis:
In account_banking_pain_base line 47, we have:

```
    party_identifier = company.sepa_creditor_identifier
```

but this field is declared in the module account_banking_sepa_direct_debit, which is not installed. The change was introduced by @pedrobaeza 24 days https://github.com/OCA/bank-payment/blame/8.0/account_banking_pain_base/models/res_company.py#L47

**Comment by alexis-via** [comment]
OK, let's make sure that this horrible bug doesn't survive the OCA code sprint.

**Comment by yvaucher** [comment]
I'm closing this as #172 was merge

cc @alexis-via @pedrobaeza
