### ISSUE TITLE
[account_payment_order] error migrating 14.0 to 15.0

### ISSUE THREAD

**Issue by atrueba** [OCA/bank-payment#1130]
Hi,

I'm in the process of migrating a 13.0 Community to the most recent version I can. I've succesfully migrated 13.0 to 14.0, but while trying to migrate from 14.0 to 15.0 I encounter the following error during account_payment_order migration:

```
error in migration script /var/lib/odoo/.local/share/Odoo/addons/15.0/account_payment_order/migrations/15.0.2.0.0/post-migration.py: no existe la relación «bank_payment_line»
LÍNEA 15:         FROM bank_payment_line bpl

Traceback (most recent call last):
  File "/var/lib/odoo/.local/lib/python3.9/site-packages/openupgradelib/openupgrade.py", line 2271, in wrapped_function
    func(
  File "/var/lib/odoo/.local/share/Odoo/addons/15.0/account_payment_order/migrations/15.0.2.0.0/post-migration.py", line 172, in migrate
    _insert_account_payments(env)
  File "/var/lib/odoo/.local/share/Odoo/addons/15.0/account_payment_order/migrations/15.0.2.0.0/post-migration.py", line 15, in _insert_account_payments
    openupgrade.logged_query(
  File "/var/lib/odoo/.local/lib/python3.9/site-packages/openupgradelib/openupgrade.py", line 1682, in logged_query
    cr.execute(query, args)
  File "<decorator-gen-3>", line 2, in execute
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 311, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: no existe la relación «bank_payment_line»
LÍNEA 15:         FROM bank_payment_line bpl
                       ^

2023-08-08 10:36:31,744 1037 WARNING database odoo.modules.loading: Transient module states were reset
2023-08-08 10:36:31,747 1037 ERROR database odoo.modules.registry: Failed to load registry
```

## Module
account_payment_order

## Environment
Debian 11.7 bullseye, amd64
Python 3.9.2-3
Odoo CE 15.0 20230807
OCA modules branch 15.0, updated to 07/08/2023

## Questions
- On the one hand, I'm aware that the migration process to 15.0 isn't completed and this may be one of the missing modules, so feel free to disregard this bug if that's the case, but I don't believe it is as this module appears under the available ones in 15.0 branch.

- One thing I find strange, if I'm gettint this right, is that v15.0.2.0.0 post-migration script is trying to do exactly the same as v14.0.2.0.0, but by the check in line 165 it should have already detected that a v14 database shouldn't need it and skip post-migration alltogether. On that regard, the v14 database (again, migrated from v13 and currently in production), doesn't include the field "old_bank_payment_line_id" that v15 is checking for, but includes an "old_bank_payment_line_name" one.

On this regard, note that my DB has the module "database_cleanup" installed and I have performed all cleanup procedures in v14 without an issue. Could be that database_cleanup has determined that "old_bank_payment_line_id" was unnecessary and deleted it? If that's the case, shouldn't v15 migration check for "old_bank_payment_line_name" instead?

Regards.

**Comment by pedrobaeza** [comment]
The problem is that you performed the DB cleanup on v14, removing the column `old_bank_payment_line_id`, and thus, the script not detecting that you already did the change to new "bank-payment style". Create manually that column for tricking this before migrating.
