### ISSUE TITLE
[16.0] bank-payment/tree/16.0/account_banking_sepa_credit_transfer error when adding bill to outgoing payment

### ISSUE THREAD

**Issue by ThijsvOers** [OCA/bank-payment#1178]
Hi, I have tested module account_banking_sepa_credit_transfer with 2 vendorbills (see screenshot from the runboat db). I was able to add the first vendorbill to the outgoing payment. The second bill gave at first the error as mentioned below the moment I tried to add the vendor bill to the payment order. 

Further testing led to to the conclusion that the error occurs when field 'Bill reference'is not filled in. Issue is that this field is not mandatory After adding the bill reference to the second vendor bill I could add the bill to the payment order.

So, in my opinion the reference bill should either be mandatory or the field should not mandatory for the outgoing payment order (I do not know what is mandatory for the sepa payment).

![image](https://github.com/OCA/bank-payment/assets/30256071/89e3fc84-2805-451c-9182-aa39ad88a149)

Error:
Traceback (most recent call last):
  File "/opt/odoo/odoo/http.py", line 1589, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/odoo/http.py", line 1616, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/odoo/http.py", line 1820, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/odoo/http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 42, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/addons/web/controllers/dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo/models.py", line 6538, in onchange
    todo = [
  File "/opt/odoo/odoo/models.py", line 6541, in <listcomp>
    if name not in done and snapshot0.has_changed(name)
  File "/opt/odoo/odoo/models.py", line 6324, in has_changed
    return self[name] != record[name]
  File "/opt/odoo/odoo/models.py", line 5897, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/opt/odoo/odoo/fields.py", line 2797, in __get__
    return super().__get__(records, owner)
  File "/opt/odoo/odoo/fields.py", line 1157, in __get__
    self.recompute(record)
  File "/opt/odoo/odoo/fields.py", line 1365, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/opt/odoo/odoo/fields.py", line 1338, in apply_except_missing
    func(records)
  File "/opt/odoo/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/opt/odoo/odoo/models.py", line 4221, in _compute_field_value
    fields.determine(field.compute, self)
  File "/opt/odoo/odoo/fields.py", line 97, in determine
    return needle(*args)
  File "/mnt/data/odoo-addons-dir/account_payment_order/models/account_payment_line.py", line 185, in _compute_payment_line
    communication_type, communication = move_line._get_communication()
  File "/mnt/data/odoo-addons-dir/account_payment_order/models/account_move_line.py", line 25, in _get_communication
    communication = self.move_id._get_payment_order_communication_full()
  File "/mnt/data/odoo-addons-dir/account_payment_order/models/account_move.py", line 94, in _get_payment_order_communication_full
    communication += " " + " ".join(references)
TypeError: sequence item 0: expected str instance, bool found

The above server error caused the following client error:
null

**Comment by pedrobaeza** [comment]
Check #1188
