### ISSUE TITLE
_prepare_move_line_default_vals() got and unexpected keyword argument 'force_balance'

### ISSUE THREAD

**Issue by sanecrab** [OCA/bank-payment#1335]
## Module
account_payment_order

## Describe the bug
When trying to close a PoS session, the following error occurs.

```
Traceback (most recent call last):
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/http.py", line 2150, in __call__
    response = request._serve_db()
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/http.py", line 1722, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/http.py", line 1749, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/http.py", line 1953, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/web/controllers/dataset.py", line 28, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/point_of_sale/models/pos_session.py", line 294, in action_pos_session_closing_control
    return session.action_pos_session_validate(balancing_account, amount_to_balance, bank_payment_method_diffs)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/point_of_sale/models/pos_session.py", line 299, in action_pos_session_validate
    return self.action_pos_session_close(balancing_account, amount_to_balance, bank_payment_method_diffs)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/point_of_sale/models/pos_session.py", line 306, in action_pos_session_close
    return self._validate_session(balancing_account, amount_to_balance, bank_payment_method_diffs)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/point_of_sale/models/pos_session.py", line 325, in _validate_session
    data = self.with_company(self.company_id).with_context(check_move_validity=False, skip_invoice_sync=True)._create_account_move(balancing_account, amount_to_balance, bank_payment_method_diffs)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/point_of_sale/models/pos_session.py", line 680, in _create_account_move
    data = self._create_bank_payment_moves(data)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/pos_online_payment/models/pos_session.py", line 39, in _create_bank_payment_moves
    data = super()._create_bank_payment_moves(data)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/point_of_sale/models/pos_session.py", line 915, in _create_bank_payment_moves
    payment_receivable_line = self._create_combine_account_payment(payment_method, amounts, diff_amount=bank_payment_method_diffs.get(payment_method.id) or 0)
  File "/opt/odoo/community/17.0/odoo-17.0/addons/point_of_sale/models/pos_session.py", line 950, in _create_combine_account_payment
    account_payment = self.env['account.payment'].create({
  File "<decorator-gen-212>", line 2, in create
  File "/opt/odoo/community/17.0/odoo-17.0/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo/community/17.0/odoo-17.0/addons/account/models/account_payment.py", line 723, in create
    to_write['line_ids'] = [(0, 0, line_vals) for line_vals in pay._prepare_move_line_default_vals(write_off_line_vals=write_off_line_vals)]
  File "/opt/odoo/pos17-ce-17.0/custom-addons/account_payment_order/models/account_payment.py", line 69, in _prepare_move_line_default_vals
    vals_list = super()._prepare_move_line_default_vals(
TypeError: AccountPayment._prepare_move_line_default_vals() got an unexpected keyword argument 'force_balance'
```

Looks like a parameter error calling the base method "_prepare_move_line_default_vals"

## To Reproduce
**Affected versions**:
Odoo v17.0

1. Open Point of Sale
2. Make sales with differents types of payment method 
3. Close Point of Sale session

**Expected behavior**
The clousure of Point of Sale session is expected to be completed, generating all the registers corresponding to accounting.

**Additional context**
OS: Ubuntu 22.04
Python: 3.10.12
Accounting: l10n-spain

**Comment by pedrobaeza** [comment]
The signature is the same:

Override here:

https://github.com/OCA/bank-payment/blob/ab9df14bca2d63191f66acfbbae384541c2bb2ca/account_payment_order/models/account_payment.py#L64

Original signature:

https://github.com/odoo/odoo/blob/2a7cf8bf3276e899bfc9a947f3b6d3fc1205e4bc/addons/account/models/account_payment.py#L287

so the problem must be in other place.

**Comment by sanecrab** [comment]
Thanks for take your time for look this.
I have realized that the problem was the signature of the method in the version of Odoo that I was using, Odoo v17 but February 2024 release.

In the current version the signature is correct as you say.

**Comment by pedrobaeza** [comment]
Yeah, you should always update all the source code together.
