### ISSUE TITLE
Statements found for unknown account

### ISSUE THREAD

**Issue by temmink** [OCA/bank-payment#14]
Dear programmers,

When I tried to import bank statements it doesn't work. 
I got the message that "Statements found for unknown account xxxxx".
![schermafbeelding 2014-07-12 om 09 56 03](https://cloud.githubusercontent.com/assets/890128/3560974/1e914dce-099f-11e4-8117-d2b99ac501a5.png)

 It seams to parse the correct format (ing structured) and recognize the correct bank statements, but it can't find my ING bankaccount number. I have setup the correct bankaccount (iban) on the company field. Bank relation information etc.

anyone knows a way to solve and/or debug this?

**Comment by hbrunn** [comment]
> anyone knows a way to solve and/or debug this?

I think you didn't create a mapping for your account. Go to Settings in the 
finance menu and create one in 'Bank accounts'

## 

Therp - Maatwerk in open ontwikkeling

Holger Brunn - Ontwerp en implementatie

mail: holger@therp.nl
web: http://therp.nl

**Comment by temmink** [comment]
In fact I did. Including a journal post for that account.
Maybe this is useful. 

I's the bankaccount created at the company form. Which is a IBAN bankaccount.
In the import log it tries to match the national bankaccount (which is a part of the iban ).

It's very strange.

after several reboots and updates. now it's seams  to try to import some of the lines, but I got the following server error:

Server Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/server/openerp/addons/account_banking/wizard/bank_import.py", line 306, in import_statements_file
    cr, uid, values, context=context)
  File "/opt/openerp/server/openerp/addons/account_banking/banking_import_transaction.py", line 686, in create
    cr, uid, vals, context)
  File "/opt/openerp/server/openerp/osv/orm.py", line 4442, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/opt/openerp/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/openerp/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for type date: ""
LINE 1: ...e_uid,create_date,write_uid,write_date) values (5,'','','','...

any one has a solution for this?

**Comment by hbrunn** [comment]
see #15
