### ISSUE TITLE
ING import failed with server error, anyone solution for this?

### ISSUE THREAD

**Issue by temmink** [OCA/bank-payment#15]
When I try to import a bankstatement file (from dutch bank ING), I got the following server error:

Server Traceback (most recent call last):
  File "/opt/openerp/server/openerp/addons/web/session.py", line 89, in send
    return openerp.netsvc.dispatch_rpc(service_name, method, args)
  File "/opt/openerp/server/openerp/netsvc.py", line 292, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/opt/openerp/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, _params)
  File "/opt/openerp/server/openerp/osv/osv.py", line 188, in execute_kw
    return self.execute(db, uid, obj, method, *args, *_kw or {})
  File "/opt/openerp/server/openerp/osv/osv.py", line 131, in wrapper
    return f(self, dbname, _args, *_kwargs)
  File "/opt/openerp/server/openerp/osv/osv.py", line 197, in execute
    res = self.execute_cr(cr, uid, obj, method, _args, *_kw)
  File "/opt/openerp/server/openerp/osv/osv.py", line 185, in execute_cr
    return getattr(object, method)(cr, uid, _args, *_kw)
  File "/opt/openerp/server/openerp/addons/account_banking/wizard/bank_import.py", line 306, in import_statements_file
    cr, uid, values, context=context)
  File "/opt/openerp/server/openerp/addons/account_banking/banking_import_transaction.py", line 686, in create
    cr, uid, vals, context)
  File "/opt/openerp/server/openerp/osv/orm.py", line 4442, in create
    cr.execute('insert into "'+self._table+'" (id'+upd0+") values ("+str(id_new)+upd1+')', tuple(upd2))
  File "/opt/openerp/server/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/opt/openerp/server/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
DataError: invalid input syntax for type date: ""
LINE 1: ...e_uid,create_date,write_uid,write_date) values (5,'','','','...

**Comment by hbrunn** [comment]
you probably need something in the line of #8 or #11 (or exactly this fix if what you import is an ING mt940 file)

**Comment by temmink** [comment]
Here I will attach some of the screens:
![bank-gegevens](https://cloud.githubusercontent.com/assets/890128/3570929/4ae44016-0b57-11e4-9635-438fdf61d05a.png)
![bank-instellingen](https://cloud.githubusercontent.com/assets/890128/3570931/4e4cd56a-0b57-11e4-9288-66fe2738739e.png)
![import-wizard](https://cloud.githubusercontent.com/assets/890128/3570937/542a30b8-0b57-11e4-9056-15fb0f24c7b9.png)

**Comment by hbrunn** [comment]
the crucial screen was the last one. Merge #8 and it should work. If so, please also give a thumbs up there

**Comment by temmink** [comment]
yes, great!!

it works much better now.
and it imported some of the statements.

only still having an issue with sometimes the bankaccount (national) not recognized).
![resultaat](https://cloud.githubusercontent.com/assets/890128/3571103/89bc194c-0b59-11e4-9912-972ef74eb84b.png)

**Comment by temmink** [comment]
btw. where can I give thumbs up :-)

**Comment by hbrunn** [comment]
Glad to hear it works. To vote that up on #8, fill in ': +1 :' without the spaces as a comment there.

You seem to have other problems with your file (given the amount of errors in transactions/statements), but that's not in the scope of this issue so I'll close this one.
