### ISSUE TITLE
account_payment_blocking make l10n-switzerland tests fail

### ISSUE THREAD

**Issue by yvaucher** [OCA/bank-payment#179]
The tests are loaded and fails.

https://travis-ci.org/OCA/l10n-switzerland/jobs/66542118

Here is the error:

```
Traceback (most recent call last):
  File "/home/travis/odoo-8.0/openerp/service/server.py", line 919, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/travis/odoo-8.0/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/travis/odoo-8.0/openerp/modules/loading.py", line 312, in load_modules
    modobj.update_list(cr, SUPERUSER_ID)
  File "/home/travis/odoo-8.0/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/travis/odoo-8.0/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/home/travis/odoo-8.0/openerp/http.py", line 1307, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/travis/odoo-8.0/openerp/modules/module.py", line 80, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/travis/bank-payment/account_payment_blocking/__init__.py", line 24, in <module>
    from . import tests
  File "/home/travis/bank-payment/account_payment_blocking/tests/__init__.py", line 23, in <module>
    from . import test_account_banking_payment_blocking
  File "/home/travis/bank-payment/account_payment_blocking/tests/test_account_banking_payment_blocking.py", line 26, in <module>
    DB = common.DB
AttributeError: 'module' object has no attribute 'DB'
```

This only failed with Odoo, OCB is working properly.

**Comment by yvaucher** [comment]
Ok this was fixed in
https://github.com/OCA/bank-payment/commit/1b6728579a2947f3640a7ad57c030d901f6e6068

Thanks

**Comment by sbidoul** [comment]
See also: https://github.com/odoo/odoo/pull/7054
