### ISSUE TITLE
[8.0] account_payment_blocking: Error after selecting invoices in creating batch

### ISSUE THREAD

**Issue by mgielissen** [OCA/bank-payment#212]
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/openerp/http.py", line 574, in dispatch
    result = self._call_function(*_self.params)
  File "/opt/odoo/odoo-server/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/service/model.py", line 113, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/http.py", line 307, in checked_call
    return self.endpoint(_a, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 803, in __call__
    return self.method(_args, *_kw)
  File "/opt/odoo/odoo-server/openerp/http.py", line 403, in response_wrap
    response = f(_args, *_kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
  File "/opt/odoo/custom/addons/account_banking_payment_export/wizard/payment_order_create.py", line 108, in search_entries
    self.extend_payment_order_domain(payment, domain)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/account_payment_partner/wizard/payment_order_create.py", line 32, in extend_payment_order_domain
    payment_order, domain)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/custom/addons/account_payment_include_draft_move/wizard/payment_order_create.py", line 37, in extend_payment_order_domain
    .extend_payment_order_domain(payment_order, domain)
  File "/opt/odoo/odoo-server/openerp/api.py", line 239, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 463, in new_api
    result = method(self._model, cr, uid, _args, *_kwargs)
  File "/opt/odoo/custom/addons/account_payment_blocking/model/payment_order_create.py", line 32, in extend_payment_order_domain
    cr, uid, payment_order, domain, context=context)
  File "/opt/odoo/odoo-server/openerp/api.py", line 241, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/opt/odoo/odoo-server/openerp/api.py", line 363, in old_api
    result = method(recs, _args, *_kwargs)
TypeError: extend_payment_order_domain() takes exactly 3 arguments (2 given)

**Comment by sbidoul** [comment]
@adrienpeiffer can you have a look at this one?

**Comment by adrienpeiffer** [comment]
Hi @mgielissen,

Can you check that you have https://github.com/OCA/bank-payment/commit/4ce30d09274128eda1d3e0192fe98ef4ba644356 ?
If yes, can you give us the steps to reproduce this problem ?

Thanks !

Adrien

**Comment by adrienpeiffer** [comment]
@mgielissen This one can be closed ?

**Comment by mgielissen** [comment]
@adrienpeiffer This can be closed. The fix from 4ce30d0 seems to work.
