### ISSUE TITLE
[7.0] account_banking_sepa_direct_debit Exception in migration when table does not exist.

### ISSUE THREAD

**Issue by NL66278** [OCA/bank-payment#228]
An error occurs in module account_banking_sepa_direct_debit when running the migration, if the table sdd_mandate does not exist.

2015-11-26 16:27:58,293 1386 INFO 2015_11_16_test openerp.modules.migration: module account_banking_sepa_direct_debit: Running migration [
0.2>] account.banking.sepa.direct_debit:: Move sdd_mandate data to account_banking_mandate
2015-11-26 16:27:58,294 1386 ERROR 2015_11_16_test openerp.sql_db: Programming error: relation "sdd_mandate" does not exist
LINE 1: ...ation, recurrent_sequence_type, type, 'CORE' FROM sdd_mandat...
                                                             ^
, in query INSERT INTO account_banking_mandate (id, create_uid, create_date, write_date, write_uid, partner_bank_id, last_debit_date, scan
, company_id, state, unique_mandate_reference, signature_date, sepa_migrated, original_mandate_identification, recurrent_sequence_type, ty
pe, scheme) SELECT id, create_uid, create_date, write_date, write_uid, partner_bank_id, last_debit_date, scan, company_id, state, unique_m
andate_reference, signature_date, sepa_migrated, original_mandate_identification, recurrent_sequence_type, type, 'CORE' FROM sdd_mandate
2015-11-26 16:27:58,294 1386 ERROR 2015_11_16_test openerp: Failed to initialize database `2015_11_16_test`.
Traceback (most recent call last):
  File "/home/odoocutst70/odoo/parts/odoo/openerp/cli/server.py", line 97, in preload_registry
    db, registry = openerp.pooler.get_db_and_pool(dbname,update_module=update_module)
  File "/home/odoocutst70/odoo/parts/odoo/openerp/pooler.py", line 33, in get_db_and_pool
    registry = RegistryManager.get(db_name, force_demo, status, update_module)
  File "/home/odoocutst70/odoo/parts/odoo/openerp/modules/registry.py", line 203, in get
    update_module)
  File "/home/odoocutst70/odoo/parts/odoo/openerp/modules/registry.py", line 233, in new
    openerp.modules.load_modules(registry.db, force_demo, status, update_module)
  File "/home/odoocutst70/odoo/parts/odoo/openerp/modules/loading.py", line 359, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odoocutst70/odoo/parts/odoo/openerp/modules/loading.py", line 264, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_chec
ks)
  File "/home/odoocutst70/odoo/parts/odoo/openerp/modules/loading.py", line 218, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoocutst70/odoo/parts/odoo/openerp/modules/migration.py", line 186, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "account_banking_sepa_direct_debit/migrations/0.2/post-consolidation.py", line 50, in migrate
  File "/home/odoocutst70/odoo/parts/odoo/openerp/sql_db.py", line 161, in wrapper
    return f(self, _args, *_kwargs)
  File "/home/odoocutst70/odoo/parts/odoo/openerp/sql_db.py", line 226, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "sdd_mandate" does not exist
LINE 1: ...ation, recurrent_sequence_type, type, 'CORE' FROM sdd_mandat...

**Comment by pedrobaeza** [comment]
I think this is already solved with current scripts.
