### ISSUE TITLE
[7.0][multicompany] Error in confirming statement line when company is different than base company

### ISSUE THREAD

**Issue by kenvac** [OCA/bank-payment#25]
[Pre-requisite]
- Multicompany module
- Accounting module

[steps to reproduce bug]
- Create bank statement for non base company
- Add statement line
- confirm statement line

[Traceback]

```
Error occurred while validating the field(s) company_id: Account and Period must belong to the same company.
Traceback (most recent call last):
  File "/home/openerp/7.0/server/openerp/netsvc.py", line 296, in dispatch_rpc
    result = ExportService.getService(service_name).dispatch(method, params)
  File "/home/openerp/7.0/server/openerp/service/web_services.py", line 626, in dispatch
    res = fn(db, uid, *params)
  File "/home/openerp/7.0/server/openerp/osv/osv.py", line 190, in execute_kw
    return self.execute(db, uid, obj, method, *args, **kw or {})
  File "/home/openerp/7.0/server/openerp/osv/osv.py", line 132, in wrapper
    return f(self, dbname, *args, **kwargs)
  File "/home/openerp/7.0/server/openerp/osv/osv.py", line 199, in execute
    res = self.execute_cr(cr, uid, obj, method, *args, **kw)
  File "/home/openerp/7.0/server/openerp/osv/osv.py", line 187, in execute_cr
    return getattr(object, method)(cr, uid, *args, **kw)
  File "/home/openerp/7.0/banking-addons/account_banking/banking_import_transaction.py", line 1562, in confirm
    statement_pool = self.pool.get('account.bank.statement')
  File "/home/openerp/7.0/banking-addons/account_banking/account_banking.py", line 405, in create_move_from_st_line
    context=localctx)
  File "/home/openerp/7.0/7.0-fixes/account_voucher/account_voucher.py", line 1645, in create_move_from_st_line
    return super(account_bank_statement, self).create_move_from_st_line(cr, uid, st_line.id, company_currency_id, next_number, context=context)
  File "/home/openerp/7.0/7.0-fixes/account/account_bank_statement.py", line 359, in create_move_from_st_line
    move_line_id = account_move_line_obj.create(cr, uid, bank_move_vals, context=context)
  File "/home/openerp/7.0/7.0-fixes/account/account_move_line.py", line 1221, in create
    result = super(account_move_line, self).create(cr, uid, vals, context=context)
  File "/home/openerp/7.0/openerp-connector/connector/producer.py", line 42, in create
    record_id = create_original(self, cr, uid, vals, context=context)
  File "/home/openerp/7.0/server/openerp/osv/orm.py", line 4567, in create
    self._validate(cr, user, [id_new], context)
  File "/home/openerp/7.0/server/openerp/osv/orm.py", line 1581, in _validate
    raise except_orm('ValidateError', '\n'.join(error_msgs))
except_osv: ('ValidateError', u'Error occurred while validating the field(s) company_id: Account and Period must belong to the same company.')
```

**Comment by kenvac** [comment]
# Possible fix

``` Python
--- a/account_banking/banking_import_transaction.py
+++ b/account_banking/banking_import_transaction.py
@@ -1600,6 +1600,8 @@ class account_bank_statement_line(orm.Model):
             st_line_number = statement_pool.get_next_st_line_number(
                 cr, uid, st_number, st_line, context)
             company_currency_id = st.journal_id.company_id.currency_id.id
+            if not context.get('company_id',False):
+                context['company_id']=st.journal_id.company_id.id
             statement_pool.create_move_from_st_line(
                 cr, uid, st_line.id, company_currency_id, st_line_number, context)
             self.write(
```

**Comment by pedrobaeza** [comment]
Is this still happening? Can you make a PR if so?

**Comment by pedrobaeza** [comment]
Closing as old version and no PR.
