### ISSUE TITLE
Not possible to valid invoice without payable/receivable

### ISSUE THREAD

**Issue by laetitia-gangloff** [OCA/bank-payment#259]
module: account_payment_blocking
version: 8.0

**Steps to reproduce**
- Create Invoice with account not payable/receivable
- Add product with account not payable/receivable
- Valid invoice

**Current behavior**

Following error message :

2016-03-17 08:21:27,770 5540 ERROR odoo-prod openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/http.py", line 539, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/http.py", line 576, in dispatch
    result = self._call_function(*_self.params)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/http.py", line 312, in _call_function
    return checked_call(self.db, *args, *_kwargs)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, _args, *_kwargs)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/http.py", line 309, in checked_call
    return self.endpoint(_a, *_kw)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/http.py", line 805, in __call__
    return self.method(_args, *_kw)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/http.py", line 405, in response_wrap
    response = f(_args, *_kw)
  File "/home/odoo-prod/instance/release/parts/odoo/addons/web/controllers/main.py", line 944, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo-prod/instance/release/parts/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, _args, *_kwargs)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-prod/instance/release/parts/odoo/addons/mail/mail_thread.py", line 187, in read_followers_data
    is_uid = uid in map(lambda x: x.id, follower.user_ids)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/fields.py", line 827, in __get__
    return record._cache[self]
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/models.py", line 6023, in __getitem__
/account
    res2 = wi.validate(signal)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/instance.py", line 80, in validate
    wi.process(signal=signal, force_running=force_running, stack=stack)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 120, in process
    ok = self._split_test(activity['split_mode'], signal, stack)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 248, in _split_test
    self._join_test(t[0], t[1], stack)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 257, in _join_test
    WorkflowItem.create(self.session, self.record, activity, inst_id, stack=stack)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 95, in create
    workflow_item.process(stack=stack)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 116, in process
    if not self._execute(activity, stack):
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 162, in _execute
    returned_action = self.wkf_expr_execute(activity)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 313, in wkf_expr_execute
    return self.wkf_expr_eval_expr(activity['action'])
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/workflow/workitem.py", line 291, in wkf_expr_eval_expr
    result = eval(line, env, nocopy=True)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/api.py", line 266, in wrapper
    return new_api(self, _args, *_kwargs)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/api.py", line 592, in new_api
    result = method(self._model, cr, uid, self.ids, _args, *_old_kwargs)
  File "/home/odoo-prod/instance/release/bank-payment/account_payment_blocking/model/account_invoice.py", line 66, in action_move_create
    context=context)
  File "/home/odoo-prod/instance/release/parts/odoo/openerp/api.py", line 268, in wrapper
    return old_api(self, _args, *_kwargs)
  File "/home/odoo-prod/instance/release/bank-payment/account_payment_blocking/model/account_invoice.py", line 44, in _update_blocked
    assert len(move_line_ids) == 1
ValueError: "" while evaluating
u'action_move_create()'

**Expected behavior**

Invoice open

**Comment by adrienpeiffer** [comment]
Hi !
In which functional case do you have this situation ?

**Comment by ismaelcj** [comment]
Hi!

I am having the same error. The error raise in an assert: https://github.com/OCA/bank-payment/blob/8.0/account_payment_blocking/model/account_invoice.py#L44 The assert checks that action_move_create only creates an account.move.line (of type payable or receivable). But if the invoice payment term has more than one due dates, then will be created two move lines.

**Comment by laetitia-gangloff** [comment]
And why it is not possible to write the flag "blocked" on all payable/receivable lines ?
(And so remove this assert)

**Comment by laetitia-gangloff** [comment]
Thank you for the fix !
