### ISSUE TITLE
Account Payment order On Enterprise Version

### ISSUE THREAD

**Issue by BelalSalahH** [OCA/bank-payment#299]
for odoo v9 while press create button on  payment order form, raise this error:

Uncaught Error: No conversion for undefined
http://localhost:8091/web/static/src/js/framework/pyeval.js:732
Traceback:
Error: No conversion for undefined
    at wrap (http://localhost:8091/web/static/src/js/framework/pyeval.js:732:29)
    at Object.**getitem** (http://localhost:8091/web/static/src/js/framework/pyeval.js:781:16)
    at Object.py.PY_getItem (http://localhost:8091/web/static/lib/py.js/lib/py.js:610:21)
    at Object.py.evaluate (http://localhost:8091/web/static/lib/py.js/lib/py.js:1403:27)
    at Object.py.evaluate (http://localhost:8091/web/static/lib/py.js/lib/py.js:1366:32)
    at Object.py.evaluate (http://localhost:8091/web/static/lib/py.js/lib/py.js:1368:27)
    at Object.py.evaluate (http://localhost:8091/web/static/lib/py.js/lib/py.js:1372:31)
    at Object.py.evaluate (http://localhost:8091/web/static/lib/py.js/lib/py.js:1397:38)
    at Object.py.evaluate (http://localhost:8091/web/static/lib/py.js/lib/py.js:1409:37)
    at Object.py.eval (http://localhost:8091/web/static/lib/py.js/lib/py.js:1453:19)

**Comment by pedrobaeza** [comment]
Not reproducible on runbot, so I close.
