### ISSUE TITLE
Error 500 on Website due to "account_payment_sale"

### ISSUE THREAD

**Issue by valentinthirion** [OCA/bank-payment#316]
[In Odoo 9.0]
Hi,

If the module "account_payment_sale" is installed, it makes crash the eCommerce Basket confirmation when confirming the address.
Seems that "onchange_partner_id" is not well inherited.

Here is my stacktrace:
2016-11-21 13:01:46,809 12164 ERROR AbAKUS_2016-11-02 openerp.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website/models/ir_http.py", line 242, in _handle_exception
    response = super(ir_http, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 158, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 786, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/base/ir/ir_http.py", line 183, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 845, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_sale/controllers/main.py", line 684, in confirm_order
    self.checkout_form_save(values["checkout"])
  File "/usr/lib/python2.7/dist-packages/openerp/addons/website_sale/controllers/main.py", line 634, in checkout_form_save
    order_obj.onchange_partner_id(cr, SUPERUSER_ID, [order.id], context=context)
TypeError: onchange_partner_id() takes exactly 1 argument (5 given)

Any help?

**Comment by pedrobaeza** [comment]
Fixed in #351
