### ISSUE TITLE
[10.0] Crash in account_payment_order

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#353]
When you create a payment order with a payment mode that has a variable link to a bank account, you get this crash:

```
Traceback (most recent call last):
  File "/home/odoo/erp/odoo/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/erp/odoo/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/erp/odoo/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/erp/odoo/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/erp/odoo/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/erp/odoo/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/erp/odoo/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/erp/odoo/addons/web/controllers/main.py", line 878, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/erp/odoo/addons/web/controllers/main.py", line 870, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/erp/odoo/odoo/api.py", line 679, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/home/odoo/erp/odoo/odoo/api.py", line 664, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/erp/usability/account_usability/account.py", line 112, in name_search
    name=name, args=args, operator=operator, limit=limit)
  File "/home/odoo/erp/odoo/odoo/models.py", line 1591, in name_search
    return self._name_search(name, args, operator, limit=limit)
  File "/home/odoo/erp/odoo/odoo/models.py", line 1604, in _name_search
    ids = self._search(args, limit=limit, access_rights_uid=access_rights_uid)
  File "/home/odoo/erp/odoo/odoo/models.py", line 4205, in _search
    query = self._where_calc(args)
  File "/home/odoo/erp/odoo/odoo/models.py", line 4006, in _where_calc
    where_clause, where_params = e.to_sql()
  File "/home/odoo/erp/odoo/odoo/osv/expression.py", line 1287, in to_sql
    q, p = self.__leaf_to_sql(leaf)
  File "/home/odoo/erp/odoo/odoo/osv/expression.py", line 1212, in __leaf_to_sql
    raise ValueError("Invalid domain term %r" % (leaf,))
ValueError: Invalid domain term (u'id', u'in', {u'company_id': 1, u'name': u'Banque BNP', u'sequence': 10})
```

This is caused by the special "domain" on journal_id in the view:

```
domain="[('id', 'in', allowed_journal_ids and allowed_journal_ids[0] and allowed_journal_ids[0][2] or [])]"
```

**Comment by adrienpeiffer** [comment]
Fixed on the following revision 5ce7b4c4ad09be4cc1282747426993f4dab40d8c
