### ISSUE TITLE
[9.0] Migration of account_payment_order

### ISSUE THREAD

**Issue by ecino** [OCA/bank-payment#368]
When trying to migrate our database to v9, the migration of module account_payment_order fails when storing values of fields from bank_payment_line. I checked my database but cannot see any incoherent data. All my payment_line records are linked to the same company, and the company itself has a valid currency (CHF).

```python
Traceback (most recent call last):
  File "/var/tmp/openupgrade/9.0/server/openerp/service/server.py", line 892, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 406, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 297, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/loading.py", line 160, in load_module_graph
    init_module_models(cr, package.name, models)
  File "/var/tmp/openupgrade/9.0/server/openerp/modules/module.py", line 317, in init_module_models
    obj_list[0].recompute(cr, openerp.SUPERUSER_ID, {})
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 5925, in recompute
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 5925, in <dictcomp>
    vals = rec._convert_to_write({n: rec[n] for n in ns})
  File "/var/tmp/openupgrade/9.0/server/openerp/models.py", line 5795, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/var/tmp/openupgrade/9.0/server/openerp/fields.py", line 830, in __get__
    self.determine_value(record)
  File "/var/tmp/openupgrade/9.0/server/openerp/fields.py", line 912, in determine_value
    self.compute_value(recs)
  File "/var/tmp/openupgrade/9.0/server/openerp/fields.py", line 892, in compute_value
    self._compute_value(records)
  File "/var/tmp/openupgrade/9.0/server/openerp/fields.py", line 882, in _compute_value
    getattr(records, self.compute)()
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/ecino/.local/share/Odoo/addons/9.0/account_payment_order/models/bank_payment_line.py", line 82, in _compute_amount
    amount_currency, bline.company_currency_id)
  File "/var/tmp/openupgrade/9.0/server/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/var/tmp/openupgrade/9.0/server/openerp/addons/base/res/res_currency.py", line 224, in compute
    assert self, "compute from unknown currency"
AssertionError: compute from unknown currency
```

**Comment by pedrobaeza** [comment]
It seems that `bline.company_currency_id` is False, so you should check why it's not filled. I think that field is a related stored one, so it seems that you have halted the update process before and thus that field was not filled.

**Comment by ecino** [comment]
Thanks for the help! I didn't halt the upgrade process, it just stopped here because of the bug. It seems the computation of all fields are done at the same time and I don't understand why the company currency is not set.
```
2017-06-14 13:48:43,635 12101 INFO r4_migrated openerp.models: Storing computed values of account.payment.order fields company_currency_id, payment_method_id
2017-06-14 13:48:43,646 12101 INFO r4_migrated openerp.models: Storing computed values of account.payment.line fields payment_type
2017-06-14 13:48:44,379 12101 INFO r4_migrated openerp.models: Storing computed values of bank.payment.line fields amount_company_currency, company_currency_id, partner_id, payment_type, state
2017-06-14 13:48:45,853 12101 INFO r4_migrated openerp.models: Actual recompute of field bank.payment.line.state for 14523 recs.
2017-06-14 13:48:52,688 12101 INFO r4_migrated openerp.models: Actual recompute of field bank.payment.line.company_currency_id for 14523 recs.
2017-06-14 13:48:56,987 12101 INFO r4_migrated openerp.models: Actual recompute of field account.payment.order.payment_method_id for 526 recs.
2017-06-14 13:48:57,081 12101 INFO r4_migrated openerp.models: Actual recompute of field account.payment.order.company_currency_id for 526 recs.
2017-06-14 13:48:58,612 12101 INFO r4_migrated openerp.models: Actual recompute of field account.payment.line.company_currency_id for 28692 recs.
2017-06-14 13:49:30,234 12101 INFO r4_migrated openerp.models: Actual recompute of field bank.payment.line.amount_company_currency for 14523 recs.
2017-06-14 13:49:36,901 12101 ERROR r4_migrated openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
(same traceback as shown above)
```

**Comment by pedrobaeza** [comment]
Well, check how that field is calculated and try to figure out why data is empty. I think it's because that data is caught from the company of the bank account, and if the bank account is not correct...

**Comment by ecino** [comment]
Still didn't find what really was the problem. I did change this line : https://github.com/OCA/bank-payment/blob/10.0/account_payment_order/models/bank_payment_line.py#L77

to this :
`for bline in self.filtered('company_id'):`

Would this be useful in a PR or not?

**Comment by pedrobaeza** [comment]
Changes should be done regularly in migration scripts, not in the rest of the code.

**Comment by StefanRijnhart** [comment]
@ecino can you try to add 'company_id' in the method's `depends`? Maybe the field is computed before the related field is 'computed', and adding the field to the dependencies will fix the order of computation.

**Comment by pedrobaeza** [comment]
Closing as no response.
