### ISSUE TITLE
Migration script error for 8.0 to 9.0

### ISSUE THREAD

**Issue by hmartinet** [OCA/bank-payment#398]
OpenUpgrade from 8.0 to 9.0. 

The problem is in my database column 'payment_order_type' does not exists, but the module account_payment_order is add by a dependency with no warranty that the field exists.

2017-10-11 10:27:48,613 31201 INFO oe_lpn_7_0_5_0_migrated openerp.modules.migration: module account_payment_order: Running migration [9.0.1.0.0>] post-migration
2017-10-11 10:27:48,614 31201 INFO oe_lpn_7_0_5_0_migrated OpenUpgrade: account_payment_order: post-migration script called with version 8.0.1.1
2017-10-11 10:27:48,614 31201 INFO oe_lpn_7_0_5_0_migrated openerp.sql_db: Programming error: column "payment_order_type" does not exist
LIGNE 3 :                        WHERE payment_order_type = 'payment'
                                       ^
, in query UPDATE account_payment_order
                       SET payment_type = 'outbound'
                       WHERE payment_order_type = 'payment'
2017-10-11 10:27:48,614 31201 ERROR oe_lpn_7_0_5_0_migrated OpenUpgrade: account_payment_order: error in migration script account_payment_order/migrations/9.0.1.0.0/post-migration.py: column "payment_order_type" does not exist
LIGNE 3 :                        WHERE payment_order_type = 'payment'
                                       ^

2017-10-11 10:27:48,615 31201 ERROR oe_lpn_7_0_5_0_migrated OpenUpgrade: column "payment_order_type" does not exist
LIGNE 3 :                        WHERE payment_order_type = 'payment'
                                       ^
Traceback (most recent call last):
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 1250, in wrapped_function
    if use_env2 else cr, version)
  File "[...]/workdir/9.0/bank-payment/account_payment_order/migrations/9.0.1.0.0/post-migration.py", line 27, in migrate
    map_payment_type(cr)
  File "[...]/workdir/9.0/bank-payment/account_payment_order/migrations/9.0.1.0.0/post-migration.py", line 15, in map_payment_type
    table='account_payment_order', write='sql')
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 1024, in map_values
    logged_query(cr, query, values)
  File "[...]/workdir/openupgradelib/openupgradelib/openupgrade.py", line 746, in logged_query
    cr.execute(query, args)
  File "[...]/workdir/9.0/server/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "[...]/workdir/9.0/server/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "payment_order_type" does not exist
LIGNE 3 :                        WHERE payment_order_type = 'payment'
                                       ^

2017-10-11 10:27:48,615 31201 ERROR oe_lpn_7_0_5_0_migrated openerp.modules.loading: Error executing post migration script for module account_payment_order
: column "payment_order_type" does not exist
LIGNE 3 :                        WHERE payment_order_type = 'payment'

**Comment by pedrobaeza** [comment]
Are you migrating or just installing the module?

**Comment by hmartinet** [comment]
Migrating

**Comment by pedrobaeza** [comment]
Then the column should be there. I have used this migration script several times without problem. Check in previous version which module contains that column for trying to trace the problem.

**Comment by hmartinet** [comment]
I have a database on 7.0 with following OCA modules installed : 
From l10n-swizerland : l10n_ch_base_bank, l10n_ch_bank, 10n_ch_payment_slip, 
From account-financial-reporting : account_financial_report_webkit

Migration from 7.0 to 8.0 done without problem
This error append in migration 8.0 to 9.0.

The module account_payment_order was not installed but it is installed automatically in 9.0 migration from one off the installed modules dependency. In 8.0 and in 9.0 I see not installed module that will create a column named payment_order_type.

**Comment by hmartinet** [comment]
Oh I found something !

The l10n-swizerland modules installed on 7.0 are not in a version form OCA... it is an old database (the goal is to migrate on Odoo 10.0) and the modules are installed with a version from Camp2Camp bzr repository... I think a have to migrate these modules to the OCA version in 7.0 database before doing the migration. Not sure it is the cause of the problem but it can be...

**Comment by pedrobaeza** [comment]
Uhm, maybe it's because you come from an v7 installation. Can you please retry installing in v8 the module account_banking_payment_export?

**Comment by hmartinet** [comment]
Ok I will try to do an update all on a v7.0 with latest version of OCA modules first (to check all needed dependencies are correctly installed on the v7.0 database before migration), then I will try your tips because at this time account_banking_payment_export was never installed by a dependency.

I will write a feedback here but not before tomorrow (it is a 500Mo database, the migration process takes time), thanks for your help.

**Comment by hmartinet** [comment]
Ok, after a discussion I will not try to solve this problem.

We are not sure to use the concerned OCA modules in the final 10.0 version. I don't want to spend times to try to solve a problem when I'm not sure we have to solve it…

I think this problem is caused by this database specific state and not by a migration bug of bank-payment project. We will decide if we have to migrate these addons after having migrate the code of our specifics addons (in one or two month I think). Then this issue can be closed.

Sorry and thanks for your help.

**Comment by metaminux** [comment]
Hello,

I triggered this issue today.
I'm running a migration from 8.0 to 10.0 on a database of 7 Go

I can see that this module is new in 9.0 and that it merges 8.0 modules : 
- account_direct_debit
- account_banking_payment_export
- account_banking_payment_transfer

Neither of them was installed in my case...

So the "account_payment_order" table just come from the previous "payment_order" table created by the "account_payment" module which doesn't contains a "payment_order_type" column (AFAIK)

In my case, a workaround is simply to comment the "map_payment_type" call from post-migration.py script.

But I suppose this could be handled better. Can we reopen this issue to investigate a bit ?

Thanks,

**Comment by pedrobaeza** [comment]
Please make the proper PR and we handle the problem there.
