### ISSUE TITLE
[11ce] Error when entering a vendor which has 2 banks on a supplier invoice 

### ISSUE THREAD

**Issue by ThijsvOers** [OCA/bank-payment#441]
Steps to reproduce:
Create a vendor with 2 bank numbers AND fill in the standard  payment mode field. Then create a new invoice and enter the name of the vendor, you will get the following error:

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-11.0/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-11.0/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-11.0/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-11.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-11.0/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-11.0/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-11.0/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-11.0/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-11.0/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-11.0/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo-11.0/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo-11.0/odoo/models.py", line 4995, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/opt/odoo/odoo-11.0/odoo/models.py", line 4891, in _onchange_eval
    method_res = method(self)
  File "/opt/odoo/custom/addons/account_banking_mandate/models/account_invoice.py", line 76, in _onchange_partner_id
    super(AccountInvoice, self)._onchange_partner_id()
  File "/opt/odoo/odoo-server/addons/purchase/models/account_invoice.py", line 111, in _onchange_partner_id
    res = super(AccountInvoice, self)._onchange_partner_id()
  File "/opt/odoo/custom/addons/account_payment_partner/models/account_invoice.py", line 38, in _onchange_partner_id
    lambda b: b.company_id == self.company_id or not
  File "/opt/odoo/odoo-11.0/odoo/fields.py", line 969, in __set__
    value = self.convert_to_cache(value, record)
  File "/opt/odoo/odoo-11.0/odoo/fields.py", line 1982, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for account.invoice.partner_bank_id: res.partner.bank(6114, 5684)

**Comment by astirpe** [comment]
This issue is caused by module `account_payment_partner`.

**Comment by astirpe** [comment]
@ThijsvOers could you check that PR https://github.com/OCA/bank-payment/pull/442 fixes this issue?
