### ISSUE TITLE
[10] error when i create a bank payment line "unknown currency"

### ISSUE THREAD

**Issue by serCliff** [OCA/bank-payment#448]
When I click on create new payment bank line, odoo throw me this error but when I close the window I can work with the module

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 677, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 935, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5503, in onchange
    newval = record[name]
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5208, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 912, in __get__
    self.determine_draft_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 1033, in determine_draft_value
    self._compute_value(record)
  File "/usr/lib/python2.7/dist-packages/odoo/fields.py", line 967, in _compute_value
    getattr(records, self.compute)()
  File "/usr/local/lib/python2.7/dist-packages/odoo/addons/account_payment_order/models/bank_payment_line.py", line 82, in _compute_amount
    amount_currency, bline.company_currency_id)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/res/res_currency.py", line 152, in compute
    assert self, "compute from unknown currency"
AssertionError: compute from unknown currency

**Comment by pedrobaeza** [comment]
Please recreate it on runbot and specify all the steps and data used.

**Comment by pedrobaeza** [comment]
I'm going to close it meanwhile we don't have more information.
