### ISSUE TITLE
[10.0] account_payment_sale: Error when partner doesn't have a valid mandate

### ISSUE THREAD

**Issue by Bilbonet** [OCA/bank-payment#459]
Creating a sale order and select a Payment Mode who needs mandate. If the partner doesn't have a valid mandate the serve shows a python error.

**Comment by pedrobaeza** [comment]
Traceback log?

**Comment by Bilbonet** [comment]
Yes, sorry.

```
Traceback (most recent call last):
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 641, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 333, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 326, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/bilbonet/odoo-estable/server/odoo/http.py", line 506, in response_wrap
    response = f(*args, **kw)
  File "/home/bilbonet/odoo-estable/server/addons/web/controllers/main.py", line 890, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/bilbonet/odoo-estable/server/addons/web/controllers/main.py", line 882, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/bilbonet/odoo-estable/server/odoo/models.py", line 5510, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/home/bilbonet/odoo-estable/server/odoo/models.py", line 5408, in _onchange_eval
    method_res = method(self)
  File "/home/bilbonet/odoo-estable/server/3addons/account_banking_mandate_sale/models/sale_order.py", line 38, in payment_mode_change
    self.mandate_id = mandates[0]
  File "/home/bilbonet/odoo-estable/server/odoo/models.py", line 5228, in __getitem__
    return self._browse((self._ids[key],), self.env)
IndexError: tuple index out of range
```

**Comment by pedrobaeza** [comment]
Fixed directly in https://github.com/OCA/bank-payment/commit/4405e43548d7821cc254c615f7098f6a11841c9a
