### ISSUE TITLE
Odoo KeyError

### ISSUE THREAD

**Issue by andercrist** [OCA/bank-payment#468]
My odoo is not starting and is indicating this error, I am not finding solution, can anyone help?

2018-04-19 14:52:48,012 1850 ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/root/odoo/odoo/service/server.py", line 252, in app
    return self.app(e, s)
  File "/root/odoo/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/root/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/root/odoo/odoo/http.py", line 1313, in __call__
    return self.dispatch(environ, start_response)
  File "/root/odoo/odoo/http.py", line 1287, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 588, in __call__
    return self.app(environ, start_response)
  File "/root/odoo/odoo/http.py", line 1460, in dispatch
    odoo.registry(db).check_signaling()
  File "/root/odoo/odoo/__init__.py", line 76, in registry
    return modules.registry.Registry(database_name)
  File "/root/odoo/odoo/modules/registry.py", line 61, in __new__
    return cls.new(db_name)
  File "/root/odoo/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/root/odoo/odoo/modules/loading.py", line 346, in load_modules
    registry.setup_models(cr)
  File "/root/odoo/odoo/modules/registry.py", line 279, in setup_models
    model._setup_fields()
  File "/root/odoo/odoo/models.py", line 2359, in _setup_fields
    field.setup_full(self)
  File "/root/odoo/odoo/fields.py", line 470, in setup_full
    self._setup_related_full(model)
  File "/root/odoo/odoo/fields.py", line 507, in _setup_related_full
    field = target._fields[name]
KeyError: 'payment_order_ok'

**Comment by pedrobaeza** [comment]
Update your modules with -u all.

**Comment by andercrist** [comment]
2018-04-19 17:07:25,123 1463 WARNING odoo odoo.modules.loading: Transient module states were reset 
2018-04-19 17:07:25,124 1463 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last): 
File "/root/odoo/odoo/modules/registry.py", line 59, in __new__ 
return cls.registries[db_name] 
File "/root/odoo/odoo/tools/func.py", line 68, in wrapper 
return func(self, *args, **kwargs) 
File "/root/odoo/odoo/tools/lru.py", line 44, in __getitem__ 
a = self.d[obj].me 
KeyError: 'odoo' 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/root/odoo/odoo/modules/registry.py", line 85, in new 
odoo.modules.load_modules(registry._db, force_demo, status, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 339, in load_modules 
force, status, report, loaded_modules, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 242, in load_marked_modules 
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks) 
File "/root/odoo/odoo/modules/loading.py", line 134, in load_module_graph 
registry.setup_models(cr) 
File "/root/odoo/odoo/modules/registry.py", line 279, in setup_models 
model._setup_fields() 
File "/root/odoo/odoo/models.py", line 2359, in _setup_fields 
field.setup_full(self) 
File "/root/odoo/odoo/fields.py", line 470, in setup_full 
self._setup_related_full(model) 
File "/root/odoo/odoo/fields.py", line 507, in _setup_related_full 
field = target._fields[name] 
KeyError: 'payment_order_ok' 
2018-04-19 17:07:25,133 1463 INFO odoo odoo.modules.loading: loading 1 modules... 




Anderson Silva / CEO-CTO 
anderson [ mailto:anderson@fazti.com.br | @fazti.com.br ] / Skype: anderson@fazti.com.br / Celular: +55 41 98839-5179 

Fazenda da Tecnologia da Informação LTDA / CNPJ: 24.574.308/0001-09 
Av. Cândido de Abreu, 469 Sala 106 - Curitiba - Paraná 
[ https://www.fazti.com.br/ | https://www.fazti.com.br ] 


De: "Pedro M. Baeza" <notifications@github.com> 
Para: "OCA/bank-payment" <bank-payment@noreply.github.com> 
Cc: "FazTI" <anderson@fazti.com.br>, "Author" <author@noreply.github.com> 
Enviadas: Quinta-feira, 19 de abril de 2018 12:14:11 
Assunto: Re: [OCA/bank-payment] Odoo KeyError (#468) 



Closed [ https://github.com/OCA/bank-payment/issues/468 | #468 ] .

**Comment by andercrist** [comment]
2018-04-19 17:19:36,979 1463 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last): 
File "/root/odoo/odoo/modules/registry.py", line 59, in __new__ 
return cls.registries[db_name] 
File "/root/odoo/odoo/tools/func.py", line 68, in wrapper 
return func(self, *args, **kwargs) 
File "/root/odoo/odoo/tools/lru.py", line 44, in __getitem__ 
a = self.d[obj].me 
KeyError: 'odoo' 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/root/odoo/odoo/http.py", line 1460, in dispatch 
odoo.registry(db).check_signaling() 
File "/root/odoo/odoo/__init__.py", line 76, in registry 
return modules.registry.Registry(database_name) 
File "/root/odoo/odoo/modules/registry.py", line 61, in __new__ 
return cls.new(db_name) 
File "/root/odoo/odoo/modules/registry.py", line 85, in new 
odoo.modules.load_modules(registry._db, force_demo, status, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 339, in load_modules 
force, status, report, loaded_modules, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 242, in load_marked_modules 
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks) 
File "/root/odoo/odoo/modules/loading.py", line 134, in load_module_graph 
registry.setup_models(cr) 
File "/root/odoo/odoo/modules/registry.py", line 279, in setup_models 
model._setup_fields() 
File "/root/odoo/odoo/models.py", line 2359, in _setup_fields 
field.setup_full(self) 
File "/root/odoo/odoo/fields.py", line 470, in setup_full 
self._setup_related_full(model) 
File "/root/odoo/odoo/fields.py", line 507, in _setup_related_full 
field = target._fields[name] 
KeyError: 'payment_order_ok' 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/root/odoo/odoo/modules/registry.py", line 59, in __new__ 
return cls.registries[db_name] 
File "/root/odoo/odoo/tools/func.py", line 68, in wrapper 
return func(self, *args, **kwargs) 
File "/root/odoo/odoo/tools/lru.py", line 44, in __getitem__ 
a = self.d[obj].me 
KeyError: 'odoo' 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/root/odoo/odoo/modules/registry.py", line 85, in new 
odoo.modules.load_modules(registry._db, force_demo, status, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 339, in load_modules 
force, status, report, loaded_modules, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 242, in load_marked_modules 
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks) 
File "/root/odoo/odoo/modules/loading.py", line 134, in load_module_graph 
registry.setup_models(cr) 
File "/root/odoo/odoo/modules/registry.py", line 279, in setup_models 
model._setup_fields() 
File "/root/odoo/odoo/models.py", line 2359, in _setup_fields 
field.setup_full(self) 
File "/root/odoo/odoo/fields.py", line 470, in setup_full 
self._setup_related_full(model) 
File "/root/odoo/odoo/fields.py", line 507, in _setup_related_full 
field = target._fields[name] 
KeyError: 'payment_order_ok' 
2018-04-19 17:19:36,984 1463 INFO odoo werkzeug: 172.17.0.1 - - [19/Apr/2018 17:19:36] "GET / HTTP/1.1" 500 - 
2018-04-19 17:19:36,989 1463 INFO odoo odoo.modules.loading: loading 1 modules... 
2018-04-19 17:19:37,070 1463 ERROR odoo werkzeug: Error on request: 
Traceback (most recent call last): 
File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 177, in run_wsgi 
execute(self.server.app) 
File "/usr/local/lib/python3.5/dist-packages/werkzeug/serving.py", line 165, in execute 
application_iter = app(environ, start_response) 
File "/root/odoo/odoo/service/server.py", line 252, in app 
return self.app(e, s) 
File "/root/odoo/odoo/service/wsgi_server.py", line 166, in application 
return application_unproxied(environ, start_response) 
File "/root/odoo/odoo/service/wsgi_server.py", line 154, in application_unproxied 
result = handler(environ, start_response) 
File "/root/odoo/odoo/http.py", line 1313, in __call__ 
return self.dispatch(environ, start_response) 
File "/root/odoo/odoo/http.py", line 1287, in __call__ 
return self.app(environ, start_wrapped) 
File "/usr/local/lib/python3.5/dist-packages/werkzeug/wsgi.py", line 588, in __call__ 
return self.app(environ, start_response) 
File "/root/odoo/odoo/http.py", line 1481, in dispatch 
response = self.get_response(httprequest, result, explicit_session) 
File "/root/odoo/odoo/http.py", line 282, in __exit__ 
elif self.registry: 
File "/root/odoo/odoo/http.py", line 373, in registry 
return odoo.registry(self.db) 
File "/root/odoo/odoo/__init__.py", line 76, in registry 
return modules.registry.Registry(database_name) 
File "/root/odoo/odoo/modules/registry.py", line 61, in __new__ 
return cls.new(db_name) 
File "/root/odoo/odoo/modules/registry.py", line 85, in new 
odoo.modules.load_modules(registry._db, force_demo, status, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 339, in load_modules 
force, status, report, loaded_modules, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 242, in load_marked_modules 
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks) 
File "/root/odoo/odoo/modules/loading.py", line 134, in load_module_graph 
registry.setup_models(cr) 
File "/root/odoo/odoo/modules/registry.py", line 279, in setup_models 
model._setup_fields() 
File "/root/odoo/odoo/models.py", line 2359, in _setup_fields 
field.setup_full(self) 
File "/root/odoo/odoo/fields.py", line 470, in setup_full 
self._setup_related_full(model) 
File "/root/odoo/odoo/fields.py", line 507, in _setup_related_full 
field = target._fields[name] 
KeyError: 'payment_order_ok' 
2018-04-19 17:19:37,106 1463 INFO odoo odoo.modules.registry: module base: creating or updating database tables 




Anderson Silva / CEO-CTO 
anderson [ mailto:anderson@fazti.com.br | @fazti.com.br ] / Skype: anderson@fazti.com.br / Celular: +55 41 98839-5179 

Fazenda da Tecnologia da Informação LTDA / CNPJ: 24.574.308/0001-09 
Av. Cândido de Abreu, 469 Sala 106 - Curitiba - Paraná 
[ https://www.fazti.com.br/ | https://www.fazti.com.br ] 


De: "Anderson Silva" <anderson@fazti.com.br> 
Para: "OCA" <reply@reply.github.com> 
Cc: "OCA" <bank-payment@noreply.github.com>, "Author" <author@noreply.github.com> 
Enviadas: Quinta-feira, 19 de abril de 2018 14:08:40 
Assunto: Re: [OCA/bank-payment] Odoo KeyError (#468) 

2018-04-19 17:07:25,123 1463 WARNING odoo odoo.modules.loading: Transient module states were reset 
2018-04-19 17:07:25,124 1463 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last): 
File "/root/odoo/odoo/modules/registry.py", line 59, in __new__ 
return cls.registries[db_name] 
File "/root/odoo/odoo/tools/func.py", line 68, in wrapper 
return func(self, *args, **kwargs) 
File "/root/odoo/odoo/tools/lru.py", line 44, in __getitem__ 
a = self.d[obj].me 
KeyError: 'odoo' 

During handling of the above exception, another exception occurred: 

Traceback (most recent call last): 
File "/root/odoo/odoo/modules/registry.py", line 85, in new 
odoo.modules.load_modules(registry._db, force_demo, status, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 339, in load_modules 
force, status, report, loaded_modules, update_module) 
File "/root/odoo/odoo/modules/loading.py", line 242, in load_marked_modules 
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks) 
File "/root/odoo/odoo/modules/loading.py", line 134, in load_module_graph 
registry.setup_models(cr) 
File "/root/odoo/odoo/modules/registry.py", line 279, in setup_models 
model._setup_fields() 
File "/root/odoo/odoo/models.py", line 2359, in _setup_fields 
field.setup_full(self) 
File "/root/odoo/odoo/fields.py", line 470, in setup_full 
self._setup_related_full(model) 
File "/root/odoo/odoo/fields.py", line 507, in _setup_related_full 
field = target._fields[name] 
KeyError: 'payment_order_ok' 
2018-04-19 17:07:25,133 1463 INFO odoo odoo.modules.loading: loading 1 modules... 




Anderson Silva / CEO-CTO 
anderson [ mailto:anderson@fazti.com.br | @fazti.com.br ] / Skype: anderson@fazti.com.br / Celular: +55 41 98839-5179 

Fazenda da Tecnologia da Informação LTDA / CNPJ: 24.574.308/0001-09 
Av. Cândido de Abreu, 469 Sala 106 - Curitiba - Paraná 
[ https://www.fazti.com.br/ | https://www.fazti.com.br ] 


De: "Pedro M. Baeza" <notifications@github.com> 
Para: "OCA/bank-payment" <bank-payment@noreply.github.com> 
Cc: "FazTI" <anderson@fazti.com.br>, "Author" <author@noreply.github.com> 
Enviadas: Quinta-feira, 19 de abril de 2018 12:14:11 
Assunto: Re: [OCA/bank-payment] Odoo KeyError (#468) 



Closed [ https://github.com/OCA/bank-payment/issues/468 | #468 ] .
