### ISSUE TITLE
[9.0] account_payment_partner : Crash in v8 to v9 migration

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#481]
With the latest version of OCA/bank-payment and the latest version of openupgradelib and the latest version of openupgrade, there is a crash when you migrate from v8 to v9 (with OCA/bank-payment in the addons_path of openupgade):

```
2018-06-04 12:57:15,697 13490 INFO testmig openerp.modules.migration: module account_payment_partner: Running migration [>9.0.1.0.0] pre-migration
2018-06-04 12:57:15,697 13490 INFO testmig openerp.modules.migration: module account_payment_partner: Running migration [>9.0.1.0.0] pre-migration
2018-06-04 12:57:15,700 13490 INFO testmig OpenUpgrade: account_payment_partner: pre-migration script called with version 8.0.0.2.0
2018-06-04 12:57:15,707 13490 INFO testmig openerp.sql_db: Programming error: syntax error at or near ")"
LINE 1: ...ment_mode_id' where model='ir.model.fields' and res_id in ()
                                                                      ^
, in query update ir_model_data set name=%s where model='ir.model.fields' and res_id in %s
2018-06-04 12:57:15,707 13490 ERROR testmig OpenUpgrade: account_payment_partner: error in migration script account_payment_partner/migrations/9.0.1.0.0/pre-migration.py: ProgrammingError('syntax error at or near ")"\nLINE 1: ...ment_mode_id\' where model=\'ir.model.fields\' and res_id in ()\n                                                                      ^\n',)
2018-06-04 12:57:15,708 13490 ERROR testmig OpenUpgrade: syntax error at or near ")"
LINE 1: ...ment_mode_id' where model='ir.model.fields' and res_id in ()
                                                                      ^
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/home/alexis/new_boite/dev/bank-payment9/account_payment_partner/migrations/9.0.1.0.0/pre-migration.py", line 21, in migrate
    'supplier_payment_mode_id',
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1706, in rename_property
    ('%s,%s' % (model, new_name), field_ids))
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 1: ...ment_mode_id' where model='ir.model.fields' and res_id in ()
                                                                      ^

2018-06-04 12:57:15,708 13490 ERROR testmig openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/loading.py", line 408, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/home/alexis/new_boite/dev/bank-payment9/account_payment_partner/migrations/9.0.1.0.0/pre-migration.py", line 21, in migrate
    'supplier_payment_mode_id',
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1706, in rename_property
    ('%s,%s' % (model, new_name), field_ids))
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 1: ...ment_mode_id' where model='ir.model.fields' and res_id in ()
                                                                      ^

2018-06-04 12:57:15,708 13490 CRITICAL testmig openerp.service.server: Failed to initialize database `testmig`.
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/service/server.py", line 897, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/loading.py", line 408, in load_modules
    force, status, report, loaded_modules, update_module, upg_registry)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/loading.py", line 299, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks, upg_registry=upg_registry)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/loading.py", line 137, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/modules/migration.py", line 169, in migrate_module
    mod.migrate(self.cr, pkg.installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1427, in wrapped_function
    if use_env2 else cr, version)
  File "/home/alexis/new_boite/dev/bank-payment9/account_payment_partner/migrations/9.0.1.0.0/pre-migration.py", line 21, in migrate
    'supplier_payment_mode_id',
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-1.3.2-py2.7.egg/openupgradelib/openupgrade.py", line 1706, in rename_property
    ('%s,%s' % (model, new_name), field_ids))
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/openupgrade9/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ProgrammingError: syntax error at or near ")"
LINE 1: ...ment_mode_id' where model='ir.model.fields' and res_id in ()
                                                                      ^

2018-06-04 12:57:15,709 13490 INFO testmig openerp.service.server: Initiating shutdown
```

It crashes in the pre-migration script recently contributed by @pedrobaeza in account_payment_partner cf https://github.com/OCA/bank-payment/blob/9.0/account_payment_partner/migrations/9.0.1.0.0/pre-migration.py

Note that 2 things need to be migrated for the M2O property fields on res.partner to payment modes: the name of the field (adds "_id" to field name) and the name of the model it points to (payment.mode to account.payment.mode).

When I run the SQL query executed at the beginning of the rename_property() method (cf https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L1693) on the v8 database with the same arguments, it works fine and returns the ID of the field. So the problem certainly come from the fact that some changes have already been made to the data before the pre-migration script of account_payment_partner is executed, leading to an empty result.

**Comment by pedrobaeza** [comment]
Uhm, strange, as the API seems straight-forward and this works migrating several DBs. Do you have a clue where is the problem? Maybe a missing module from the original bank-payment set?

**Comment by alexis-via** [comment]
I have no idea for the moment, and I'm not an openupgrade expert. On my previous migration, I patched the method rename_property() in openupgradelib so that it doesn't crash when field_ids is empty, but I haven't investigated it either.

My scenario:
- I create a demo v8 database and install account_payment_partner
- I set some customer and supplier payment modes on some partners
- I run the v8 to v9 migration via openupgarde with OCA/bank-payment/9.0 in the addons_path
-> it always crashes.

**Comment by pedrobaeza** [comment]
OK, I'll check to see, but I think one valid patch is to not continue on that empty value.

**Comment by jonerikceberio** [comment]
Confirmed, the update of the ir_model_fields does not find any fields. However the field is in the DB. So @alexis-via explanation sounds fine: the field has been previously changed in the cache

**Comment by miquelalzanillas** [comment]
Can anyone tell how can I patch the rename_property()?
```python
def rename_property(cr, model, old_name, new_name):
    """Rename property old_name owned by model to new_name. This should happen
    in a pre-migration script."""
    cr.execute(
        "update ir_model_fields f set name=%s "
        "from ir_model m "
        "where m.id=f.model_id and m.model=%s and f.name=%s "
        "returning f.id",
        (new_name, model, old_name))
    field_ids = tuple(i for i, in cr.fetchall())
    cr.execute(
        "update ir_model_data set name=%s where model='ir.model.fields' and "
        "res_id in %s",
        ('%s,%s' % (model, new_name), field_ids))
    cr.execute(
        "update ir_property set name=%s where fields_id in %s",
        (new_name, field_ids))
```
Thanks in advance.
