### ISSUE TITLE
[10.0][account_payment_partner] Cannot print Vendor bill

### ISSUE THREAD

**Issue by elicoidal** [OCA/bank-payment#501]
When trying to print a vendor bill I get the following traceback:
```
Traceback (most recent call last):
  File "/home/openerp/instance/odoo-community10/parts/odoo/addons/report/controllers/main.py", line 96, in report_download
    response = self.report_routes(reportname, docids=docids, converter='pdf')
  File "/home/openerp/instance/odoo-community10/parts/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/home/openerp/instance/odoo-community10/parts/odoo/addons/report/controllers/main.py", line 45, in report_routes
    pdf = report_obj.with_context(context).get_pdf(docids, reportname, data=data)
  File "/home/openerp/instance/odoo-community10/parts/edi/account_invoice_ubl/models/report.py", line 20, in get_pdf
    docids, report_name, html=html, data=data)
  File "/home/openerp/instance/odoo-community10/parts/mis-builder/mis_builder/report/mis_report_instance_qweb.py", line 24, in get_pdf
    docids, report_name, html=html, data=data)
  File "/home/openerp/instance/odoo-community10/parts/odoo/addons/report/models/report.py", line 178, in get_pdf
    html = self.with_context(context).get_html(docids, report_name, data=data)
  File "/home/openerp/instance/odoo-community10/parts/odoo/addons/report/models/report.py", line 144, in get_html
    return self.render(report.report_name, docargs)
  File "/home/openerp/instance/odoo-community10/parts/odoo/addons/report/models/report.py", line 120, in render
    return view_obj.render_template(template, values)
  File "/home/openerp/instance/odoo-community10/parts/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1049, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/home/openerp/instance/odoo-community10/parts/odoo/addons/website/models/ir_ui_view.py", line 115, in render
    return super(View, self).render(values, engine=engine)
  File "/home/openerp/instance/odoo-community10/parts/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/home/openerp/instance/odoo-community10/parts/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1069, in render
    return self.env[engine].render(self.id, qcontext)
  File "/home/openerp/instance/odoo-community10/parts/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/home/openerp/instance/odoo-community10/parts/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/home/openerp/instance/odoo-community10/parts/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: unsupported operand type(s) for +: 'bool' and 'str'
Traceback (most recent call last):
  File "/home/openerp/instance/odoo-community10/parts/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_account_report_invoice_document_6797
  File "<template>", line 3, in body_call_content_6796
TypeError: unsupported operand type(s) for +: 'bool' and 'str'

Error to render compiling AST
TypeError: unsupported operand type(s) for +: 'bool' and 'str'
Template: account.report_invoice_document
Path: /templates/t/t/div/p[4]/t
Node: <t t-esc="o.partner_bank_id.bank_id.name + ('' if not o.partner_bank_id.bank_id.bic else ' (' + o.partner_bank_id.bank_id.bic + ')')"/>
```                
cc @pedrobaeza @sbidoul

**Comment by pedrobaeza** [comment]
Look at the code:

https://github.com/OCA/bank-payment/blob/3cdb2b4a052e217d2efd636eaba799f7dca86269/account_payment_partner/views/report_invoice.xml#L12-L14

This is not possible unless you have a bank without name, which can't be possible as the bank name is required.

**Comment by elicoidal** [comment]
Internal data issue.
