### ISSUE TITLE
[12.0] account_payment_order: error when printing a "payment order " or a "debit order"

### ISSUE THREAD

**Issue by eduardgm** [OCA/bank-payment#549]
What are the steps to reproduce this issue?

I go to Invoicing/Accounting --> Payments --> Payment Orders/Debit Orders. After that, I select a record and click on the "Print" button. An error like this appears:

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1673, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter)
  File "/opt/odoo/custom/src/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 1614, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 677, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 710, in render_qweb_html
    data = self._get_rendering_context(docids, data)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_actions_report.py", line 723, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
AttributeError: 'report.account_payment_order.print_account_payment' object has no attribute '_get_report_values'

**Comment by pedrobaeza** [comment]
Fixed in #580
