### ISSUE TITLE
[12.0] account_banking_sepa_direct_debit: creating transfer file

### ISSUE THREAD

**Issue by ghost** [OCA/bank-payment#600]
```


Odoo Server Error

Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/share/odoo/odoo/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/share/odoo/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/share/odoo/odoo/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/usr/share/odoo/odoo/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/share/odoo/odoo/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/share/odoo/odoo/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/usr/share/odoo/odoo/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/usr/share/odoo/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/share/odoo/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/share/odoo/odoo/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/share/odoo/odoo/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/share/odoo/3rd-addons/account_payment_order/models/account_payment_order.py", line 332, in open2generated
    payment_file_str, filename = self.generate_payment_file()
  File "/usr/share/odoo/3rd-addons/account_banking_sepa_direct_debit/models/account_payment_order.py", line 88, in generate_payment_file
    key = (line.date, priority, categ_purpose, seq_type, scheme)
UnboundLocalError: local variable 'seq_type' referenced before assignment
```
This Errormessage displayed when i want to create paymentfile.

**Comment by pedrobaeza** [comment]
You have a mandate defined as "Generic Mandate". The valid ones are "Recurrent" or "One-Off".

I have put code for raising an error in this case: 7d64216916e15c2a275e1f1b5058f17e21f38912

**Comment by ghost** [comment]
thx. @pedrobaeza  nice sunday service :-) 
now i can try next step.
Error:
Element '{urn:iso:std:iso:20022:tech:xsd:pain.008.003.02}LclInstrm': This element is not expected. Expected is ( {urn:iso:std:iso:20022:tech:xsd:pain.008.003.02}SvcLvl )., line 28 

i try a few settings, but dont know whats wrong.

**Comment by pedrobaeza** [comment]
I'm afraid that's on your side.
