### ISSUE TITLE
[12.0] account_banking_mandeate: upgrade-error, dont find openupgradelib

### ISSUE THREAD

**Issue by ghost** [OCA/bank-payment#614]
Hello,
upgrading modules ends with this message:
2019-07-15 10:29:27,601 40 ERROR dbase odoo.modules.migration: module account_banking_mandate: Unable to load pre-migration file account_banking_mandate/migrations/12.0.2.0.0/pre-migration.py 
Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/modules/migration.py", line 181, in migrate_module
    mod = load_script(pyfile, name)
  File "/usr/share/odoo/odoo/odoo/modules/migration.py", line 46, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/odoo/3rd-addons/account_banking_mandate/migrations/12.0.2.0.0/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
ModuleNotFoundError: No module named 'openupgradelib'
2019-07-15 10:29:27,605 40 WARNING dbase odoo.modules.loading: Transient module states were reset 
2019-07-15 10:29:27,606 40 ERROR dbase odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/usr/share/odoo/odoo/odoo/modules/migration.py", line 181, in migrate_module
    mod = load_script(pyfile, name)
  File "/usr/share/odoo/odoo/odoo/modules/migration.py", line 46, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/odoo/3rd-addons/account_banking_mandate/migrations/12.0.2.0.0/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
ModuleNotFoundError: No module named 'openupgradelib'
2019-07-15 10:29:27,606 40 CRITICAL dbase odoo.service.server: Failed to initialize database `dbase`. 
Traceback (most recent call last):
  File "/usr/share/odoo/odoo/odoo/service/server.py", line 1116, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/usr/share/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/share/odoo/odoo/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/usr/share/odoo/odoo/odoo/modules/migration.py", line 181, in migrate_module
    mod = load_script(pyfile, name)
  File "/usr/share/odoo/odoo/odoo/modules/migration.py", line 46, in load_script
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/share/odoo/3rd-addons/account_banking_mandate/migrations/12.0.2.0.0/pre-migration.py", line 4, in <module>
    from openupgradelib import openupgrade
ModuleNotFoundError: No module named 'openupgradelib'
2019-07-15 10:29:27,607 40 INFO dbase odoo.service.server: Stopping gracefully 

Please, which module(s) i have to install for "openupgrade"?

**Comment by pedrobaeza** [comment]
It's a Python library: https://github.com/OCA/openupgradelib

**Comment by ghost** [comment]
thx. upgrade well done.
