### ISSUE TITLE
Crash in v8 to v9 migration

### ISSUE THREAD

**Issue by alexis-via** [OCA/bank-payment#616]
I'm migrating a DB from v7 to v12 with openupgrade, and I get a crash in the migration from v8 to v9 using the latest code of bank-payment for v9. Up-to-date bank-payment v8 was in the addons_path during the migration from v7 to v8.

```
2019-07-16 06:27:38,382 15778 DEBUG testmig2 OpenUpgrade: Running
                    INSERT INTO ir_model_data (
                        name, date_init, date_update, module, model, res_id
                    ) VALUES (
                        field_account_payment_line_payment_type, (now() at time zone 'UTC'),
                        (now() at time zone 'UTC'), account_payment_order, ir.model.fields, 12023
                    )
2019-07-16 06:27:38,382 15778 DEBUG testmig2 OpenUpgrade: 1 rows affected
2019-07-16 06:27:38,383 15778 DEBUG testmig2 OpenUpgrade: Running ALTER TABLE bank_payment_line ADD 
COLUMN partner_id int4
2019-07-16 06:27:38,383 15778 DEBUG testmig2 OpenUpgrade: -1 rows affected
2019-07-16 06:27:38,386 15778 INFO testmig2 openerp.sql_db: bad query:
            INSERT INTO ir_model_fields (
                model_id, model, name, field_description, ttype, state
            ) VALUES (
                743, 'bank.payment.line', 'partner_id', 'OU', 'many2one', 'base'
            ) RETURNING id
2019-07-16 06:27:38,386 15778 ERROR testmig2 OpenUpgrade: Error running
            INSERT INTO ir_model_fields (
                model_id, model, name, field_description, ttype, state
            ) VALUES (
                743, 'bank.payment.line', 'partner_id', 'OU', 'many2one', 'base'
            ) RETURNING id
2019-07-16 06:27:38,386 15778 ERROR testmig2 OpenUpgrade: account_payment_order: error in migration 
script account_payment_order/migrations/9.0.1.0.0/pre-migration.py: IntegrityError('duplicate key va
lue violates unique constraint "ir_model_fields_name_model_uniq"\nDETAIL:  Key (name, model_id)=(par
tner_id, 743) already exists.\n',)
2019-07-16 06:27:38,386 15778 ERROR testmig2 OpenUpgrade: duplicate key value violates unique constr
aint "ir_model_fields_name_model_uniq"
DETAIL:  Key (name, model_id)=(partner_id, 743) already exists.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupg
rade.py", line 1502, in wrapped_function
    if use_env2 else cr, version)
  File "/data/odoo/migration/openupgrade9/bank-payment/account_payment_order/migrations/9.0.1.0.0/pr
e-migration.py", line 239, in migrate
    populate_computed_fields(env)
  File "/data/odoo/migration/openupgrade9/bank-payment/account_payment_order/migrations/9.0.1.0.0/pr
e-migration.py", line 172, in populate_computed_fields
    'monetary', False, 'account_payment_order'),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupg
rade.py", line 1962, in add_fields
    (model_id, model_name, field_name, 'OU', field_type, 'base'),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupg
rade.py", line 986, in logged_query
    cr.execute(query, args)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_fields_name_model_uniq"
DETAIL:  Key (name, model_id)=(partner_id, 743) already exists.

2019-07-16 06:27:38,388 15778 ERROR testmig2 openerp.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1502, in wrapped_function
    if use_env2 else cr, version)
  File "/data/odoo/migration/openupgrade9/bank-payment/account_payment_order/migrations/9.0.1.0.0/pre-migration.py", line 239, in migrate
    populate_computed_fields(env)
  File "/data/odoo/migration/openupgrade9/bank-payment/account_payment_order/migrations/9.0.1.0.0/pre-migration.py", line 172, in populate_computed_fields
    'monetary', False, 'account_payment_order'),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1962, in add_fields
    (model_id, model_name, field_name, 'OU', field_type, 'base'),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 986, in logged_query
    cr.execute(query, args)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_fields_name_model_uniq"
DETAIL:  Key (name, model_id)=(partner_id, 743) already exists.

2019-07-16 06:27:38,388 15778 CRITICAL testmig2 openerp.service.server: Failed to initialize database `testmig2`.
Traceback (most recent call last):
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1502, in wrapped_function
    if use_env2 else cr, version)
  File "/data/odoo/migration/openupgrade9/bank-payment/account_payment_order/migrations/9.0.1.0.0/pre-migration.py", line 239, in migrate
    populate_computed_fields(env)
  File "/data/odoo/migration/openupgrade9/bank-payment/account_payment_order/migrations/9.0.1.0.0/pre-migration.py", line 172, in populate_computed_fields
    'monetary', False, 'account_payment_order'),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1962, in add_fields
    (model_id, model_name, field_name, 'OU', field_type, 'base'),
  File "/usr/local/lib/python2.7/dist-packages/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 986, in logged_query
    cr.execute(query, args)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/data/odoo/migration/openupgrade9/openupgrade/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_fields_name_model_uniq"
DETAIL:  Key (name, model_id)=(partner_id, 743) already exists.
```

This crash was not present with OCA/bank-payment code v9 from 3 months ago. So, for me, the regression has been introduced by this commit by @pedrobaeza  : https://github.com/OCA/bank-payment/commit/59dd1394e0a4435399512c2a26858e17be7ddd0d
The partner_id field on bank.payment.line already exists in bank-payment v8 (https://github.com/OCA/bank-payment/blob/8.0/account_banking_payment_export/models/bank_payment_line.py#L18) : it is a non-stored related field. But it means that the partner_id field of bank.payment.line is present in the table ir_model_fields in v8. Then, if you look at the code of add_field() in openupgradelib (cf https://github.com/OCA/openupgradelib/blob/master/openupgradelib/openupgrade.py#L1887), you see that it doesn't check if the field already exists in ir_model_fields.

So I don't know if this bug must be fixed in openupgradelib or bank-payment v9.

**Comment by pedrobaeza** [comment]
Yes, my fault rewriting these scripts when I face a DB migration with literally billions of payment lines. I suppose I didn't get the problem as I was adding things interactively doing the migration, and add it as SQL in my demo DB and put finally in the script the add field sentence.

Thanks for detecting the problem and the wide bug report.

Fixed in 7386158, as openupgradelib shouldn't check these conditions, because everything goes in pack: if you have the field, you have all the entries the method populates. It's the duty of the caller to make sure of this.
