### ISSUE TITLE
[11.0] account_banking_sepa_direct_debit: access addon l10n_generic_coa from tests but it is not added as a dependency

### ISSUE THREAD

**Issue by ljsalvatierra-binovo** [OCA/bank-payment#628]
Hi, I've encountered the following error when running the tests of the addon _account_banking_sepa_direct_debit_ because I've not installed _l10n_generic_coa_.

```
2019-09-03 10:23:50,159 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ERROR
2019-09-03 10:23:50,160 10930 INFO testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ======================================================================
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ERROR: test_financed_sdd (odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd.TestSDD)
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: Traceback (most recent call last):
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/tools/cache.py", line 84, in lookup
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     r = d[key]
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/tools/func.py", line 68, in wrapper
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     return func(self, *args, **kwargs)
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/tools/lru.py", line 44, in __getitem__
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     a = self.d[obj].me
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ` KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f2e573b5d08>, 'l10n_generic_coa.configurable_chart_template')
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ` 
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ` During handling of the above exception, another exception occurred:
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ` 
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ` Traceback (most recent call last):
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/addons-unmodified/account_banking_sepa_direct_debit/tests/test_sdd.py", line 46, in setUp
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     'l10n_generic_coa.configurable_chart_template'
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/api.py", line 794, in ref
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/addons/base/ir/ir_model.py", line 1367, in xmlid_to_object
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/addons/base/ir/ir_model.py", line 1351, in xmlid_to_res_model_res_id
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     return self.xmlid_lookup(xmlid)[1:3]
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "<decorator-gen-21>", line 2, in xmlid_lookup
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/tools/cache.py", line 89, in lookup
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     value = d[key] = self.method(*args, **kwargs)
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `   File "/home/odoo/submodules/ocb/odoo/addons/base/ir/ir_model.py", line 1340, in xmlid_lookup
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: `     raise ValueError('External ID not found in the system: %s' % xmlid)
2019-09-03 10:23:50,160 10930 ERROR testing odoo.addons.l10n_es_account_banking_sepa_fsdd.tests.test_l10n_es_account_banking_sepa_fsdd: ` ValueError: External ID not found in the system: l10n_generic_coa.configurable_chart_template
```

For what I've seen the test was modified on 27349263d36f2fd98c20985e69241e8f9699e6b3

https://github.com/OCA/bank-payment/blob/94c8e6a8aed6af197daa96e87240752417e855dc/account_banking_sepa_direct_debit/tests/test_sdd.py#L46

Kind regards and thank you for your time.

**Comment by pedrobaeza** [comment]
`l10n_generic_coa` is auto-installed on demo databases, so it's expected to be present in tests. Putting as a hard dependency in manifest would force regular users to install the module.

What is your use case where the module is not installed? Do you have any other solution?

**Comment by ljsalvatierra-binovo** [comment]
> `l10n_generic_coa` is auto-installed on demo databases, so it's expected to be present in tests. Putting as a hard dependency in manifest would force regular users to install the module.
> 
> What is your use case where the module is not installed? Do you have any other solution?

It is not auto-installed on demo databases always, only when you specify a _country_code_ that installs a localization addon with the _l10n_generic_coa_ as a dependency. If you create a demo database with the _country_code_ **es**, the addon **l10n_es** is installed instead of **l10n_us** (which have l10n_generic_coa as a dependency).

The problem I'm facing is because I run the tests with the spanish localization.

**Comment by pedrobaeza** [comment]
There are 2 implicit rules for doing tests: put your language in English and your country in US. If not, you will find a lot of problems in Odoo and OCA modules. The second one will be possible to be changed in v13, but not before. Any way, you don't need to change that country for installing `l10n_es` by dependencies and test whatever you need.

**Comment by ljsalvatierra-binovo** [comment]
> There are 2 implicit rules for doing tests: put your language in English and your country in US. If not, you will find a lot of problems in Odoo and OCA modules. The second one will be possible to be changed in v13, but not before. Any way, you don't need to change that country for installing `l10n_es` by dependencies and test whatever you need.

I understand that I don't need to change the country, the problem with that approach is not been able to test our customers custom configuration, which don't have **l10n_us** installed.
With your clarification I close the issue, thank you again for your time. Kind regards.
