### ISSUE TITLE
[9.0] account_payment_order : Crash in v8 to v9 migration

### ISSUE THREAD

**Issue by gabrielcardoso21** [OCA/bank-payment#640]
I'm having this problem in the migration from v8 to v9

Traceback (most recent call last):
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/modules/registry.py", line 390, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/modules/loading.py", line 446, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check, upg_registry)
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/modules/loading.py", line 331, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check, upg_registry=upg_registry
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/modules/loading.py", line 151, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/modules/migration.py", line 170, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/home/gabrielcardoso/migration/m9/eggs/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 1430, in wrapped_function
    if use_env2 else cr, version)
  File "/home/gabrielcardoso/migration/m9/parts/bank-payment/account_payment_order/migrations/9.0.1.0.0/pre-migration.py", line 241, in migrate
    populate_computed_fields(env)
  File "/home/gabrielcardoso/migration/m9/parts/bank-payment/account_payment_order/migrations/9.0.1.0.0/pre-migration.py", line 161, in populate_computed_fields
    cr, "ALTER TABLE bank_payment_line ADD partner_id int4",
  File "/home/gabrielcardoso/migration/m9/eggs/openupgradelib-2.0.0-py2.7.egg/openupgradelib/openupgrade.py", line 925, in logged_query
    cr.execute(query, args)
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/gabrielcardoso/migration/m9/parts/odoo/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "bank_payment_line" does not exist

**Comment by pedrobaeza** [comment]
It seems you don't have fully upgraded the module with latest v8 code.
