### ISSUE TITLE
[Bug] account_payment_partner compatibility with odoo 8.0

### ISSUE THREAD

**Issue by jbarascut** [OCA/bank-payment#7]
Hi, 
After an update, this addons doesn't work

2014-07-09 12:44:50,278 23258 CRITICAL prod140709 openerp.modules.module: Couldn't load module account_payment_partner
2014-07-09 12:44:50,278 23258 CRITICAL prod140709 openerp.modules.module: **init**() takes exactly 1 argument (7 given)
2014-07-09 12:44:50,282 23258 INFO prod140709 werkzeug: 81.220.68.236 - - [09/Jul/2014 12:44:50] "GET / HTTP/1.1" 500 -
2014-07-09 12:44:50,286 23258 ERROR prod140709 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/share/pyshared/werkzeug/serving.py", line 159, in run_wsgi
    execute(app)
  File "/usr/share/pyshared/werkzeug/serving.py", line 146, in execute
    application_iter = app(environ, start_response)
  File "/opt/openerp/odoo/openerp/service/server.py", line 280, in app
    return self.app(e, s)
  File "/opt/openerp/odoo/openerp/service/wsgi_server.py", line 216, in application
    return application_unproxied(environ, start_response)
  File "/opt/openerp/odoo/openerp/service/wsgi_server.py", line 202, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/openerp/odoo/openerp/http.py", line 1165, in **call**
    return self.dispatch(environ, start_response)
  File "/opt/openerp/odoo/openerp/http.py", line 1142, in **call**
    return self.app(environ, start_wrapped)
  File "/usr/share/pyshared/werkzeug/wsgi.py", line 411, in **call**
    return self.app(environ, start_response)
  File "/opt/openerp/odoo/openerp/http.py", line 1297, in dispatch
    ir_http = request.registry['ir.http']
  File "/opt/openerp/odoo/openerp/http.py", line 228, in registry
    return openerp.modules.registry.RegistryManager.get(self.db) if self.db else None
  File "/opt/openerp/odoo/openerp/modules/registry.py", line 291, in get
    update_module)
  File "/opt/openerp/odoo/openerp/modules/registry.py", line 322, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 361, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 268, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/openerp/odoo/openerp/modules/loading.py", line 152, in load_module_graph
    load_openerp_module(package.name)
  File "/opt/openerp/odoo/openerp/modules/module.py", line 301, in load_openerp_module
    __import__('openerp.addons.' + module_name)
  File "/opt/openerp/odoo/openerp/modules/module.py", line 76, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/opt/openerp/community/banking/account_payment_partner/**init**.py", line 23, in <module>
    from . import model
  File "/opt/openerp/community/banking/account_payment_partner/model/**init**.py", line 23, in <module>
    from . import partner
  File "/opt/openerp/community/banking/account_payment_partner/model/partner.py", line 26, in <module>
    class res_partner(orm.Model):
  File "/opt/openerp/community/banking/account_payment_partner/model/partner.py", line 33, in res_partner
    help="Select the default payment mode for this supplier."),
TypeError: **init**() takes exactly 1 argument (7 given)

Thanks

**Comment by bwrsandman** [comment]
It is very likely that none of these modules have been ported.

**Comment by jbarascut** [comment]
likely,

before my update this morning, the modules worked

2014-07-09 14:52 GMT+02:00 Sandy notifications@github.com:

> It is very likely that none of these modules have been ported.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/banking/issues/7#issuecomment-48465480.

## 

Cordialement

**Comment by alexis-via** [comment]
in the current code (which is for v7):
'customer_payment_mode': fields.property(
            'payment.mode', type='many2one', relation='payment.mode',
            string='Customer Payment Mode', view_load=True,
            help="Select the default payment mode for this customer."),

for v8, you should try this:

'customer_payment_mode': fields.property(
            type='many2one', relation='payment.mode',
            string='Customer Payment Mode',
            help="Select the default payment mode for this customer."),

and do the same for the other fields.property in the code.

**Comment by bwrsandman** [comment]
@alexis-via 

for codeblocks use backticks (`)

> ```
> a code block
> ```

gives

```
a code block
```

**Comment by rvalyi** [comment]
@alexis-via it's like in our wiki ;-)

**Comment by jbarascut** [comment]
Perfect, thanks Alexis.

2014-07-11 6:10 GMT+02:00 Raphaël Valyi notifications@github.com:

> @alexis-via https://github.com/alexis-via it's like in our wiki ;-)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OCA/banking/issues/7#issuecomment-48692635.

## 

Cordialement

**Comment by pedrobaeza** [comment]
Please check #35 for a full migration of this and other modules.
