### ISSUE TITLE
Error when installing SEPA module in Odoo v14

### ISSUE THREAD

**Issue by lucasvossen** [OCA/bank-payment#882]
## Module
payment_sepa_direct_debit

## Describe the bug
Odoo Server Error
Traceback (most recent call last):

## To Reproduce
v14 of odoo

1. Go to Apps
2. Search payment_sepa_direct_debit
3. Try to install

**Expected behavior**
1. Install the module

**Additional context**
Error code:

Fout:
Odoo Server Error

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/odoo/models.py", line 4220, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/odoo/models.py", line 4149, in _load_records_create
    return self.create(values)
  File "<decorator-gen-43>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 482, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-65>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/odoo/models.py", line 3910, in create
    fields[0].determine_inverse(batch_recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1187, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 300, in _inverse_arch
    view.write(data)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 500, in write
    res = super(View, self).write(self._compute_defaults(vals))
  File "/home/odoo/src/odoo/odoo/models.py", line 3694, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/home/odoo/src/odoo/odoo/models.py", line 1266, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 408, in _check_xml
    raise ValidationError(_(
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 391, in _check_xml
    view.postprocess_and_fields(view_doc, validate=True)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 851, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 863, in _postprocess_view
    self.postprocess(node, [], editable, name_manager)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 963, in postprocess
    self.postprocess(child, current_node_path, node_info['editable'], name_manager)
  [Previous line repeated 1 more time]
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 942, in postprocess
    postprocessor(node, name_manager, node_info)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 999, in _postprocess_tag_field
    xarch, sub_name_manager = self.with_context(
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 865, in _postprocess_view
    name_manager.check_view_fields(self)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 2009, in check_view_fields
    view.handle_view_error(msg)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_ui_view.py", line 673, in handle_view_error
    raise ValueError(formatted_message).with_traceback(from_traceback) from from_exception
odoo.exceptions.ValidationError: Fout bij het valideren van weergave:

Veld available_partner_bank_ids dat wordt gebruikt in field partner_bank_id default domain ([('id', 'in', available_partner_bank_ids)]) moet aanwezig zijn in de weergave, maar ontbreekt.

View name: sdd.account.batch.payment.form.inherit
Error context:
 view: ir.ui.view(7022,)
 xmlid: view_batch_payment_form_inherit
 view.model: account.batch.payment
 view.parent: ir.ui.view(1048,)
 file: /home/odoo/src/enterprise/account_sepa_direct_debit/views/account_batch_payment_views.xml

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/odoo/src/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 459, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 347, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/odoo/tools/convert.py", line 681, in _tag_root
    raise ParseError('while parsing %s:%s, near\n%s' % (
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/account_sepa_direct_debit/views/account_batch_payment_views.xml:5, near
<record id="view_batch_payment_form_inherit" model="ir.ui.view">
            <field name="name">sdd.account.batch.payment.form.inherit</field>
            <field name="model">account.batch.payment</field>
            <field name="inherit_id" ref="account_batch_payment.view_batch_payment_form"/>
            <field name="arch" type="xml">
                <data><xpath expr="//field[@name='name']" position="after">
                    <field name="sdd_required_collection_date" attrs="{'required': [('payment_method_code','=','sdd')], 'invisible': [('payment_method_code','!=','sdd')]}"/>
                    <field name="sdd_batch_booking" string="Batch Booking" attrs="{'invisible': [('payment_method_code','!=','sdd')]}"/>
                    <field name="sdd_scheme" attrs="{'readonly': [('state', '!=', 'draft')], 'invisible': [('payment_method_code','!=','sdd')], 'required': [('payment_method_code','==','sdd')]}"/>
                </xpath>
                <field name="payment_ids" position="attributes">
                    <attribute name="domain">
                ['|', ('payment_method_id.code', '!=', 'sdd'), ('sdd_mandate_id.sdd_scheme', '=', sdd_scheme), ('batch_payment_id', '=', False), ('state', 'not in', ['reconciled', 'cancelled']), ('payment_method_id', '=', payment_method_id), ('journal_id', '=', journal_id), ('payment_type','=',batch_type)]
                    </attribute>
                </field>
            </data></field>
        </record>

**Comment by lucasvossen** [comment]
We use no third party apps

**Comment by alexis-via** [comment]
@lucasvossen you're using the ENTERPRISE module, not the OCA module !!!
