### ISSUE TITLE
Error when add new payment method

### ISSUE THREAD

**Issue by rr10** [OCA/bank-payment#896]
## Module
account.payment.mode odoo 15

https://user-images.githubusercontent.com/26082390/152379331-605c08fb-2fe9-4f37-9015-6874b5982909.mp4

RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo15/odoo/odoo/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo15/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo15/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo15/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1335, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo15/odoo/addons/web/controllers/main.py", line 1327, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 462, in call_kw
    result = _call_kw_model_create(method, model, args, kwargs)
  File "/opt/odoo15/odoo/odoo/api.py", line 442, in _call_kw_model_create
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-189>", line 2, in create
  File "/opt/odoo15/odoo/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/opt/odoo15/odoo/addons/account/models/account_payment_method.py", line 28, in create
    if information.get('mode') == 'multi':
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo15/odoo/odoo/http.py", line 643, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo15/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by cspaniard** [comment]
I am encountering the same problem... is it related to these modules or do you think I might me something else wrong elsewhere.

The truth of the matter is that I cannot add any new payment methods.

Please help...
TIA
David

PS: @rr10 did you find a solution / workaround for this ?

**Comment by pedrobaeza** [comment]
Not a problem of the OCA module: https://github.com/OCA/bank-payment/pull/1079#issuecomment-1544741393
