### ISSUE TITLE
[15.0] Error when installing account chart - account_payment_mode

### ISSUE THREAD

**Issue by fkantelberg** [OCA/bank-payment#977]
## Module
account_payment_mode

## Describe the bug
The order of installation matters for `account_payment_mode`, a payment provider and an account chart causing crashes during automatic installations and manual installations. While for manual installations there is a workaround a workaround for automatic installations can be more tricky.

## To Reproduce
**Affected versions**: 15.0

1. Fresh Odoo installation
2. Install the modules `account_payment_mode` and a payment module (e.g. `payment_stripe`)
3. Install an account chart (e.g. `l10n_de_skr04`)

**Expected behavior**
If the installation happens in this order it produces an error and the installation of the account chart fails. I expect that the order of installation doesn't matter for the modules `account_payment_mode`, `payment_stripe` and `l10n_de_skr04`.

**Additional context**
```
2022-10-28 06:42:44,147 11 INFO odoo odoo.modules.loading: loading l10n_de_skr03/data/account_chart_template_data.xml
2022-10-28 06:42:49,714 11 WARNING odoo odoo.modules.loading: Transient module states were reset
2022-10-28 06:42:49,723 11 ERROR odoo odoo.modules.registry: Failed to load registry
2022-10-28 06:42:49,723 11 ERROR odoo odoo.http: Exception during JSON request handling.
...
  File "/tmp/addons/account/models/account_journal.py", line 437, in _check_payment_method_line_ids_multiplicity
    raise ValidationError(_("Some payment methods supposed to be unique already exists somewhere else.\n"
    odoo.exceptions.ValidationError: Some payment methods supposed to be unique already exists somewhere else.
    ([stripe] Stripe (inbound))

    View error context:
    '-no context-'
```

As far as I can see the bug is caused by the overwriting of `_default_outbound_payment_methods` and `_default_inbound_payment_methods` of `account.journal` of the mentioned module. If I remove those lines it works again. I'm not experienced enough with the in-depth accounting here to decide if this would be the right approach or it should be handled differently. Please support me here.

**Comment by astirpe** [comment]
I just faced this issue in V16 as well. Installing `account_payment_mode` fails when combined with any Payment Provider and any COA

**Steps to reproduce:**

1. create a simple installing module, with the manifest having the combination of the three modules as dependencies, for example:

```python
    "depends": [
        "payment_mollie",
        "account_payment_mode",
        "l10n_generic_coa",
    ],
```

2. install the module
 
 **Result:**

```
2023-04-25 11:24:07,344 75393 INFO dbname odoo.modules.loading: loading l10n_generic_coa/data/l10n_generic_coa_post.xml 
2023-04-25 11:24:08,631 75393 WARNING dbname odoo.modules.loading: Transient module states were reset 
2023-04-25 11:24:08,636 75393 ERROR dbname odoo.modules.registry: Failed to load registry 
2023-04-25 11:24:08,636 75393 CRITICAL dbname odoo.service.server: Failed to initialize database `dbname`. 
Traceback (most recent call last):
  File "/odoo/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/odoo/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/odoo/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/odoo/odoo/modules/loading.py", line 487, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/odoo/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/odoo/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/odoo/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/odoo/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/odoo/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/odoo/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/odoo/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /odoo/addons/l10n_generic_coa/data/l10n_generic_coa_post.xml:81
Some payment methods supposed to be unique already exists somewhere else.
([mollie] Mollie (inbound))
View error context:
'-no context-'
```


**Reason:**

Module `account_payment_mode` overrides `def _default_inbound_payment_methods()` and this seems the cause of the issue:

1. Odoo by default sets the Payment Method of a payment provider to unique: https://github.com/odoo/odoo/blob/16.0/addons/account_payment/models/account_payment_method.py#L17
2. By installing `account_payment_mode` and one Payment Provider module (eg.: Mollie), the `_default_inbound_payment_methods()` takes into account the Mollie Payment Provider.
3. When installing the COA module, the try-to-install method triggers `_check_payment_method_line_ids_multiplicity()`, which raises error https://github.com/odoo/odoo/blob/16.0/addons/account/models/account_journal.py#L464-L465

If the override of `def _default_inbound_payment_methods()` is removed, the error doesn't occur.

**Comment by pedrobaeza** [comment]
@ThomasBinsfeld you added such code in 257289dfb2902b23e795ff2dc1e19da17da2e58f

Do you remember why that override?
